### PR TITLE
update org.maplibre.gl to version 9.5.2

### LINKED ISSUE #2349: Exodus tracker finds GMS classes
Last time we did this we were looking at apktool and decompiled classes, fixed in https://github.com/deltachat/deltachat-android/pull/2303

F-Droid now integrates _(but not yet enforces)_ Exodus trackers scanning capabilities, and we scanned the current repo and we're in the middle of a clean up.

See long thread here: https://gitlab.com/fdroid/fdroidserver/-/issues/1004

In this scan DeltaChat popped up again but Element did not (!!)
```
$fdroid scanner --verbose --exodus com.b44t.messenger_632.apk
DEBUG: Starting new HTTPS connection (1): reports.exodus-privacy.eu.org:443
DEBUG: https://reports.exodus-privacy.eu.org:443 "GET /api/trackers HTTP/1.1" 200 None
DEBUG: 428 trackers signatures loaded
INFO: Scanning APK with dexdump for known non-free classes.
DEBUG: > /usr/bin/dexdump /tmp/tmpw_8kem8z/classes.dex
DEBUG: > /usr/bin/dexdump /tmp/tmpw_8kem8z/classes2.dex
DEBUG: Found class 'com/google/android/gms/tasks/OnFailureListener'
DEBUG: Found class 'com/google/android/gms/location/LocationResult'
DEBUG: Found class 'com/google/android/gms/location/FusedLocationProviderClient'
DEBUG: Found class 'com/google/android/gms/location/LocationRequest'
DEBUG: Found class 'com/google/android/gms/location/LocationCallback'
DEBUG: Found class 'com/google/android/gms/tasks/OnSuccessListener'
CRITICAL: Found problems in /home/fdroid/scanner/com.b44t.messenger_632.apk
WARNING: Scanner found 6 problems in /home/fdroid/scanner/com.b44t.messenger_632.apk:
```

Looking at deps
```
$gradle dependencies --configuration fatReleaseCompileClasspath
...
+--- org.maplibre.gl:android-sdk:9.4.0
|    +--- com.mapbox.mapboxsdk:mapbox-sdk-geojson:5.3.0
|    |    \--- com.google.code.gson:gson:2.8.6
|    +--- com.mapbox.mapboxsdk:mapbox-android-gestures:0.7.0
|    \--- com.mapbox.mapboxsdk:mapbox-android-accounts:0.7.0
...
```

First thing `com.mapbox.mapboxsdk:mapbox-android-accounts` is not-FOSS see [maven](https://mvnrepository.com/artifact/com.mapbox.mapboxsdk/mapbox-android-accounts/0.7.0) and [this issue](https://github.com/mapbox/mapbox-gl-native-android/issues/316)

Also not sure why maplibre still depends on com.mapbox, but that's another issue I guess.

apktool > com.b44t.messenger_632/smali_classes2/
```
$ grep gms -rin 
/com/mapbox/mapboxsdk/location/engine/GoogleLocation...smali
8<-----moar of this
...
```
...coming from here I guess https://github.com/maplibre/maplibre-gl-native/blob/android-v9.4.0/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/engine/GoogleLocationEngineImpl.java#L13

/LE: disabled 631&632 https://gitlab.com/fdroid/fdroiddata/-/commit/bbe1be46dffe071335d24296133b9815edfe198d

### PR DESCRIPTION
**Pull request by adbenitez**
hopefully closes #2349

### CODE REVIEW

**Comment by adbenitez** [comment]
just updating the version number won't do, the api changed:
```
/home/dc/projects/deltalab-android/src/org/thoughtcrime/securesms/map/MapActivity.java:71: error: no suitable method found for getInstance(Context,String)
            Mapbox.getInstance(context, BuildConfig.MAP_ACCESS_TOKEN);      
                  ^                                                                                                                                                                                                              
    method Mapbox.getInstance(Context) is not applicable
      (actual and formal argument lists differ in length)  
    method Mapbox.getInstance(Context,String,WellKnownTileServer) is not applicable                                                                                                                                              
      (actual and formal argument lists differ in length)                                                                                                                                                                        
/home/dc/projects/deltalab-android/src/org/thoughtcrime/securesms/map/MapActivity.java:114: error: cannot find symbol
        mapFragment.getMapAsync(mapboxMap -> mapboxMap.setStyle(Style.MAPBOX_STREETS, style -> {                                                                                                                                 
                                                                     ^
  symbol:   variable MAPBOX_STREETS                                                                             
  location: class Style
```

I am not really deep in this part of the code and would take more time to read and understand and fix in emacs without much help from the editor wrt autocompletion etc. so maybe @Hocuri if you know how to fix this quickly feel free to take over the PR

**Comment by adbenitez** [comment]
ok I am fixing it already, it is not that hard following the notes on https://github.com/maplibre/maplibre-gl-native/pull/90

**Review by r10s — APPROVED** [review]
looks good, i also build+tested on one device.

thanks a looooooooooooooooott! <3

**Comment by adbenitez** [comment]
yeah, analyzing the apk now and following the steps from https://github.com/deltachat/deltachat-android/issues/2349#issuecomment-1192871784 now the `mapbox-android-account` stuff is gone :tada:

**Comment by adbenitez** [comment]
@r10s feel free to merge, I am back AFK "offline"/dc-only mode :D

**Pull request merged**
