### PR TITLE
hide "add contact manually" for chatmail accounts

### LINKED ISSUE #3163: "create contact manually" option is confusing for chatmail
many chatmail users for some reason (if it can go wrong it will go wrong) end up selecting the option to add contact manually in the QR scanning screen instead of sharing invitation link, adding contact manually is not recommended and will not work at all if user adds an address from another server instance

### PR DESCRIPTION
**Pull request by adbenitez**
close #3163

### CODE REVIEW

**Comment by hpk42** [comment]
i guess this shouldn't be merged/released without also caring for https://github.com/deltachat/deltachat-android/issues/3164  ?

**Comment by adbenitez** [comment]
https://github.com/deltachat/deltachat-android/issues/3164 is not a blocker for this PR, although together they improve the "get in contact situation", but already not going the path to add a contact manually will lead users to scan QR or use the share button and discover the invite link instead of falling in the "message can be delivered unencrypted" trap after adding manually

**Comment by r10s** [comment]
removing this option would probably already push users to "share", as that is the only viable option left. 

downside of the PR is that it removes the option to contact users from the same instance using just the email address - but then again, if you share the address, you can probably also share the link.

but yes, that all should be regarded in the "larger picture" of "make inviting friends" easier, but already alone, it removes one pitfall

**Comment by adbenitez** [comment]
> downside of the PR is that it removes the option to contact users from the same instance using just the email address -

sending unencrypted messages on the same instance should not be a use case we should support and in fact it will be better for chatmail operators legally-wise if such possibility is removed

**Comment by iequidoo** [comment]
The problem maybe is that you can't readd a deleted contact then. Now it works because the peerstate isn't deleted, so you can send encrypted messages to the readded contact and the chat is verified from the beginning. I checked this on my Android.

**Comment by r10s** [comment]
> The problem maybe is that you can't readd a deleted contact then. Now it works because the peerstate isn't deleted, so you can send encrypted messages to the readded contact and the chat is verified from the beginning. I checked this on my Android.

i do not really understand. iirc, ["contacts in use" anyways are not really deleted](https://github.com/deltachat/deltachat-core-rust/pull/3751) (as they are referenced) but their origin is decreased so that they do not appear in add-contact-UI (but eg. still as group members).

anyways, if there is an issue with deletion/recreation, that should be fixed in a way we do not need "add contact manually"

**Comment by iequidoo** [comment]
> i do not really understand. iirc, ["contacts in use" anyways are not really deleted](https://github.com/deltachat/deltachat-core-rust/pull/3751) (as they are referenced) but their origin is decreased so that they do not appear in add-contact-UI (but eg. still as group members).
> 
> anyways, if there is an issue with deletion/recreation, that should be fixed in a way we do not need "add contact manually"

True, contacts in use can't be really deleted, but anyway currently the only way to look up such a contact is "Add Contact Manually". So despite you still have the contact's peerstate, you can't chat with them again. I don't think this really prevents merging the PR, this isn't a frequent scenario, but probably even for chatmail it makes sense to have some fallback option to add a contact by an address.

**Comment by r10s** [comment]
> but probably even for chatmail it makes sense to have some fallback option to add a contact by an address.

if doing the same as for initially adding a contact works again after deletion, that seems enough, totally fine and reasonable.

concretely, as long as tapping or scanning the contact's invite code works also for once deleted contacts, things are fine. if this is not working for re-adding a contact, that's a bug.

**Comment by iequidoo** [comment]
> if doing the same as for initially adding a contact works again after deletion, that seems enough, totally fine and reasonable.
> 
> concretely, as long as tapping or scanning the contact's invite code works also for once deleted contacts, things are fine. if this is not working for re-adding a contact, that's a bug.

If the user has the invite code, i guess it should work. But this is not always the case, e.g. if the user shared their own invite code instead. Ok, i think it's not that important, now it works only because peerstates are never cleaned up.

**Review by r10s — APPROVED** [review]

**Pull request merged**
