### PR TITLE
fortify wording in delete-server dialog

### PR DESCRIPTION
**Pull request by r10s**
this pr changes the wording, not relativize things, underlining the worse impact.

i avoided adding "maybe" or "potentially" here, even if that would be more accurate as in reality fewer messages are deleted (we could add a "Info" link or so at some point, but that is more work and can be done later).

before/after screenshots:

### CODE REVIEW

**Comment by gerryfrancis** [comment]
@r10s Very transparent! :+1:

**Comment by Hocuri** [comment]
1. :+1: 
2. Maybe "Do not use this function if you are using other email clients **than**/**besides** Delta Chat
3. I liked the sentence "This will also delete emails affected by the 'show classic emails' option", OTOH it's very technical, maybe "This includes **~all~** emails in all folders, **not only chat messages**"? (bold means that I propose to change it, not to make it bold:wink:)
  I'd also be in favor of leaving out the word "all" because technically it's not correct that all emails are deleted - if `show_emails` is off, some emails are not deleted and people should not rely on that _all_ emails are deleted.
  :+1: for the wording "in all folders" as this is going to be the case as soon as my `scan_folders` is implemented
4. @elwerene what do you think?

**Comment by elwerene** [comment]
@Hocuri I think it is a lot better now! I didn't know it would delete my normal emails when I activated this feature and with this dialog it's very clear!

**Review by Hocuri — APPROVED** [review]
Then let's approve so @r10s can merge it quickly after applying my suggestions (or reading through my suggestions and not liking them, whatever, it's probably most important to fortify wording at all)

**Comment by r10s** [comment]
- i stroke the first "all", i think it is still strong by the "from all server folders".
- yip, you're probably right,  "beside" seems to be more correct
- mentioning the "show all emails option" - i tried to avoid that as this seems to be part of the problem: ppl may think "fine" at the moment the deletion is enabled and forget about this bit later. therefore, being quite negative seems to be better here. and yes, it is too complicated.
- i did not add "not only chat messages" as this seems to be pretty clear and would make the sentence a bit too complicated imho



thanks for approving, but i would like to leave the pr a little bit open to allow more comments (we do not have core50 yet anyway, so 1.14.5 won't be done before tomorrow anyway)

**Comment by Hocuri** [comment]
- it's "beside***s***":joy:
- concerning "not only chat messages": My suggestion had been to remove "media and 'Saved Messages'" instead, so that the sentence becomes: "This includes emails in all folders, not only chat messages".
  However, of all my suggestions, this one was the least important to me so if you would like to keep "media and 'Saved Messages'", still :+1:

**Comment by Hocuri** [comment]
> i was not aware there is a difference :) thanks for taking care about such details!

Ok I looked it up now, and sources disagree on this (I had thought you had just typed it wrongly) but if there is a difference then it's that ["beside" means "next to" while "besides" means "in addition to"](https://www.grammarly.com/blog/beside-vs-besides/). So, it was ok before but now it's perfect :)

**Comment by Hocuri** [comment]
BTW I wanted to say how much I enjoy the way we discuss such things in general. I mean, we had totally different opinions in the beginning on a topic that feels so important (of course it does, it is important) and yet we got to a consensus without even starting to repeat arguments (feeling not understood).

**Comment by r10s** [comment]
totally agree, @Hocuri 👍

**Pull request merged**
