### PR TITLE
fix that ndk make didn't work with symlinked core

### PR DESCRIPTION
**Pull request by Simon-Laux**

### CODE REVIEW

**Comment by Hocuri** [comment]
Looks fine, but why does it help?
- How do you get a symlinked core?
- Why is `../something` not the same as `$jnidir/something` if the last thing you did was `jnidir=$(pwd); cd some_directory`
- I once read that it's better to use `$PWD` instead of `$(pwd)`

**Comment by Simon-Laux** [comment]
> How do you get a symlinked core?

```
ln -s ../../deltachat-core-rust jni/deltachat-core-rust
```
the first path needs to be replaced with the location of your core repo clone ( in my case it's right next to the `deltachat-android` folder)

> Why is `../something` not the same as `$jnidir/something` if the last thing you did was `jnidir=$(pwd); cd some_directory`

it seems like relative paths are relativ to the current real folder path, not to the symbolic link path. at least for the `cp` command.

> I once read that it's better to use `$PWD` instead of `$(pwd)`

`$(pwd)` works for me, if you want we can try the other one, but I'm not after perfectionism here. I just needed it myself to work with a symlinked core.

**Review by Hocuri — APPROVED** [review]
Ok, so I pushed a commit to use `$PWD`.

Do you use MacOS? If not, we might want to wait a bit for @r10s to test this on MacOS, too

**Review by adbenitez — APPROVED** [review]

**Comment by r10s** [comment]
`echo $PWD` works on mac, so i would assume the whole pr is fine on mac as well.

**Pull request merged**
