### PR TITLE
hide toolbar onStop and show it again onResume to avoid bug with keyboard

### LINKED ISSUE #2798: title bar disappears sometimes
the title bar disappears sometimes, currently this is reproducible on the phone of @hpk42 

- send a message (virtual keyboard is still on) EDIT: no need to send just type is enough (or even just an open keyboard)
- turn screen off, wait 5+ seconds, turn screen on again

-> the title bar is gone. it reappears eg. when virtual keyboard is hidden

you may need to try this several times until it happens

### PR DESCRIPTION
**Pull request by adbenitez**
close #2798

### CODE REVIEW

**Review by r10s — APPROVED** [review]
another try! thanks a lot for holding one!

**Comment by adbenitez** [comment]
> another try! thanks a lot for holding one!

hopefully this time is finally fixed, unless it re-appears after trying about 100 times in a row :unamused:

**Comment by adbenitez** [comment]
more logs:
```
11-08 18:09:49.615  1466  7157 W ActivityTaskManager: Force removing ActivityRecord{7a87ff0 u0 com.b44t.messenger.beta/org.thoughtcrime.securesms.ConversationActivity t4347 f}}: app died, no saved state
11-08 18:09:49.616  1466  1695 W UsageStatsService: Unexpected activity event reported! (com.b44t.messenger.beta/org.thoughtcrime.securesms.ConversationActivity event : 23 instanceId : 223988073)
```

```
11-08 18:14:01.916  3562  3562 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.                                                                                                                          
11-08 18:14:01.916  3562  3562 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
```

**Comment by adbenitez** [comment]
I think the issue is that fat-debug apk is slower and there the issue happens a lot less than in release-mode apk, will have to switch to testing with release-mode compiled apks

**Comment by r10s** [comment]
yeah, i also had the feeling it is related to device speed - eg. initially we could reproduce it nearly all times, but in the debugger only one of 20 times or so ...

this bug is a hard one, thanks for taking care!

**Comment by adbenitez** [comment]
the issue is solved with this hack: 
* onPause, hide the bar, 
* onResume display the bar

I did this only if keyboard is open to reduce potential issues, but so far it works nice and it is not noticeable

**Comment by r10s** [comment]
is it really required to hide the bar?

this sounds to me like the more dangerous part.

in any case, please add a comment that describes precisely that this is a hack and which cornercase that aims to solve

**Comment by adbenitez** [comment]
> is it really required to hide the bar?

yes, if the bar is not hidden, the issue appears again, at the time onResume() if you check for the bar's visibility it says it is visible, if you anyway call bar.show() it doesn't work, it is like it is crashed in some weird state caused by the keyboard display effect



> this sounds to me like the more dangerous part.

indeed I just realized the onPause() is called also when going back to the chatlist and in its visible the bar disappears while in the transition animation, so I just improved it now this is the current behavior:

only hide the toolbar onStop() AND if keyboard is open AND screen is off

this is a constrained scenario and hiding the toolbar onStop() ensures it is hidden when the activity is no longer visible (onPause() is called when the activity is no longer in foreground but could be still visible, like in the go-to-chatlist transition)

if onStop() was called then onResume() should also be called, it can't happen that the activity was stopped (and the toolbar hidden) and then onResume() is not called, so this should be safe

**Comment by adbenitez** [comment]
> in any case, please add a comment that describes precisely that this is a hack and which cornercase that aims to solve

done :heavy_check_mark:

**Comment by adbenitez** [comment]
good points, I updated according to your suggestions! :+1:

**Comment by r10s** [comment]
and now: fingers crossed!

**Pull request merged**
