### PR TITLE
gradle: use default debug keystore path

### PR DESCRIPTION
**Pull request by vitalyster**

### CODE REVIEW

**Comment by r10s** [comment]
I'm no Android expert. What is this change for?

**Comment by vitalyster** [comment]
Android build tools provide debug keystore automatically, with this change no need to create one

**Comment by r10s** [comment]
Okay, thank you very much. 

@toddy15 I do not think, this will affect F-Droid.

**Comment by r10s** [comment]
I've reverted your commit, I tried to explain the reasons here https://github.com/deltachat/deltachat-android#build

I'm not sure, if there is a better way to achieve using the same keyfile on different machines. But for now, I do not want to lose all my testing device installations.

However, anyway thank you for your pull request that at least started this discussion. Any further pull request are welcome and I'm looking forward to them :-)

Best regards,
Björn

**Comment by vitalyster** [comment]
You can just put your keystore in '~/.android/debug.keystore', isn't it?

**Comment by r10s** [comment]
I swear, it did not worked for me as I tried it first. Maybe I did something wrong.

However, yes, finally this seems to work. However, won't this get complicated for developers developing different apps?

**Comment by vitalyster** [comment]
That was the main reason to make things easier for those who already develop different apps :) I have contributed to multiple projects and never saw debug keystore path redefinition.

**Comment by r10s** [comment]
Okay.

But as there are already existing development setup out there and such a change may force the requirement of reinstalling Delta and losing all chats, I think it is a good idea to use config/debug.keystore if it exist. If not, we use the default.  Sth. like this https://gist.github.com/lifuzu/8009968

This would not require extra steps on new setups and leaves old setups intact.

What do you think about this?

**Comment by vitalyster** [comment]
like this? https://github.com/vitalyster/deltachat-android/commit/e5507d77629224943ad58f581c17c711f1949fda

**Comment by r10s** [comment]
This looks perfect to me :)
Do you like to create a pull request?

**Comment by vitalyster** [comment]
done. We can also call ndk-build automatically and get rid of ndk-build line in readme too :) Are there any issues with auto build?

**Comment by r10s** [comment]
Not as far as I know. I simply have no gradle android experiences; the gradle files is a copy of Telegram-FOSS. 
We only should keep in mind that it has to work on F-Droid.

**Pull request merged**
