### PR TITLE
Notification fixes

### PR DESCRIPTION
**Pull request by cyBerta**

### CODE REVIEW

**Comment by hpk42** [comment]
while you are doing notification fixes -- would/could the behaviour
improve for when a lot (say 30 messages, some of them bigger)
are pending?  currently, it's vibrating/making a sound every
few seconds, for a long time.  This happens when travelling
or otherwise being offline for longer times but still participating
in chatty chats.

**Comment by r10s** [comment]
@hpk42 i think, at least part of the problem is that on program start, _all_ unread mails are notified, not only the "fresh" ones. this will be changed. 

i think we'll see how this works out and already mitigates the problem. if not, we can iterate from there.

the problem are a bit the new "notification channels" where you have few control about a single message that is notified ("notification channels" are a MUST to be used when targeting the most recent android-versions :/

**Comment by cyBerta** [comment]
> while you are doing notification fixes -- would/could the behaviour
> improve for when a lot (say 30 messages, some of them bigger)
> are pending?

Sure, I'll work on that.

**Comment by hpk42** [comment]
On Thu, May 16, 2019 at 03:03 -0700, cyBerta wrote:
> > while you are doing notification fixes -- would/could the behaviour
> > improve for when a lot (say 30 messages, some of them bigger)
> > are pending?
> 
> Sure, I'll work on that.

no big worries, not a high prio. It only occurs if you have very 
busy chats and offline times in between, so i wouldn't classify it 
as "immediate annoyance when starting to use the app".

**Comment by cyBerta** [comment]
@hpk42 I silenced all notifications within the first minute after app start. I tried it out and it helps a lot regarding the described issue.

**Comment by hpk42** [comment]
On Thu, May 16, 2019 at 10:54 +0000, cyBerta wrote:
> @hpk42 I silenced all notifications within the first minute after app start. I tried it out and it helps a lot regarding the described issue. 

but if the app is killed (from Android) wouldn't it then be silence, not notify? 
or are you talking about the sound?

**Comment by cyBerta** [comment]
> but if the app is killed (from Android) wouldn't it then be silence, not notify? or are you talking about the sound?

I'm talking about the sound. All messages appear in the notification bar as expected.

**Comment by r10s** [comment]
> I'm talking about the sound. All messages appear in the notification bar as expected.

"All messages" are "all new incoming messages" then, right?
"old" messages that are already downloaded are not notified again then? i think that was part of the issue - and the main difference between signal-ui and telegram-ui.

**Comment by cyBerta** [comment]
> "All messages" are "all new incoming messages" then, right?

Exactly.

**Comment by r10s** [comment]
some comments:

- cleaning up notifications when entering a chat works as expected

- if there are two chats with unread notifications, say ChatA (1 unread) and ChatB (2 unread) and a new message comes in to Chat A, the app rings 3 times - 1 time for ChatA and again the 2 times for ChatB. The app should only for new messages propagaged by DC_EVENT_INCOMING_MSG - nb: just had a look: the old telegram-ui did rely completely on that event and uses dc_get_fresh_msgs() only to remove items from the notification bar. maybe this is the better approach to not notify too often.

- if we're in ChatA and a new messages comes in for ChatB this is not notified until the chatlist is opened again.  
i am not deep in the logic, however, also this should not happen when reacting mainly on DC_EVENT_INCOMING_MSG and using "current chat", "app is active" only as secondary signals to decide about show/dontShow, priority, sound on/off.  
i think entering/leaving an activity should trigger any notifications at all.

- for in-chat-sounds i'd use the sound-files i mentioned at https://github.com/deltachat/deltachat-android/issues/451#issuecomment-492772270

**Comment by r10s** [comment]
i think the clear-notification-code also causes the other chats to be notified again ...

**Comment by cyBerta** [comment]
>     * if we're in ChatA and a new messages comes in for ChatB this is not notified until the chatlist is opened again.
>       i am not deep in the logic, however, also this should not happen when reacting mainly on DC_EVENT_INCOMING_MSG and using "current chat", "app is active" only as secondary signals to decide about show/dontShow, priority, sound on/off.
>       i think entering/leaving an activity should trigger any notifications at all.

This behavior is intended. The idea behind it is: As long as people write in a chat, they should not be disturbed by incoming notifications from different chats. Those incoming notifications are in a pending state. they will be deliviered as soon, as the the user is not in a chat view anymore. It addresses the issue described here: https://github.com/deltachat/deltachat-android/issues/451#issuecomment-456504011

**Comment by cyBerta** [comment]
>     * if there are two chats with unread notifications, say ChatA (1 unread) and ChatB (2 unread) and a new message comes in to Chat A, the app rings 3 times - 1 time for ChatA and again the 2 times for ChatB. The app should only for new messages propagaged by DC_EVENT_INCOMING_MSG - nb: just had a look: the old telegram-ui did rely completely on that event and uses dc_get_fresh_msgs() only to _remove_ items from the notification bar. maybe this is the better approach to not notify too often.

uff, thanks for the hint!!!

**Comment by cyBerta** [comment]
>     * for in-chat-sounds i'd use the sound-files i mentioned at [#451 (comment)](https://github.com/deltachat/deltachat-android/issues/451#issuecomment-492772270)

The app has an option to set individual notification sounds per chat. Shall I remove that option?

**Comment by cyBerta** [comment]
>     * if there are two chats with unread notifications, say ChatA (1 unread) and ChatB (2 unread) and a new message comes in to Chat A, the app rings 3 times - 1 time for ChatA and again the 2 times for ChatB. The app should only for new messages propagaged by DC_EVENT_INCOMING_MSG - nb: just had a look: the old telegram-ui did rely completely on that event and uses dc_get_fresh_msgs() only to _remove_ items from the notification bar. maybe this is the better approach to not notify too often.

I cannot reproduce that. Can we have a short direct chat session?

**Comment by cyBerta** [comment]
Oh, I oversaw that comment: https://github.com/deltachat/deltachat-android/issues/451#issuecomment-492772270. Will implement it

**Pull request merged**
