### PR TITLE
fix formatting for gplay store

### PR DESCRIPTION
**Pull request by hpk42**
@r10s please upload it -- i didn't change content, just formatting which doesn't look good on gplay.

### CODE REVIEW

**Comment by r10s** [comment]
> Shouldn't we translate the play store description?

yip, in general, this makes probably sense, however, not sure if it is really needed for the beta version.

**Comment by r10s** [comment]
@hpk42 thanks for the update, uploaded it to gplay (will take some hours or so until really updated there, however)

**Comment by webratte** [comment]
> in general, this makes probably sense, however, not sure if it is really needed for the beta version.

You have more then 1000 downloads. And I think the description for
version 1.0 will be the same.
And it would be great to start v.1.0 with much translations as possible.
That makes DC more international ;-)
Isn't it?

**Comment by r10s** [comment]
not sure if the release will have the same description.
however, i thing sooner or later, we'll have translations, however, it seems to be some effort, not only for the translators.

**Comment by webratte** [comment]
OK, probably your right.

**Pull request merged**
