### PR TITLE
[WIP] implement TimerIntentService 

### PR DESCRIPTION
**Pull request by cyBerta**
to work around possible broadcast receiver timeouts

### CODE REVIEW

**Comment by cyBerta** [comment]
This doesn't fix https://github.com/deltachat/deltachat-android/issues/1099, but prevent's the described force close. 
The actual bug is in the core's triggered by interruptImapIdle()

**Comment by r10s** [comment]
@cyBerta do you think this would fix https://github.com/deltachat/deltachat-android/issues/1104 ?

**Comment by webratte** [comment]
If you would offer a apk witch contains this PR I would make a factory reset of my test phone.

This way I could simulate a fresh install on a new, not optimized, phone like non tech users do.

**Comment by r10s** [comment]
i think we should got for #1108, WorkManager instead.

**Pull request closed without merging**
