### PR TITLE
set notification group only for Android API 24+

### LINKED ISSUE #1525: Old Android not getting notified
Os: Android
Delta Chat version :1.11.0
Android version: 4.2.2 or 4.4.2 maybe more
Expected Behavior: on get message from server, the user receive a notification
Actual Behavior: the notification does not appear, with or without the reliable background connection setting

In the 1.8.1 it works ok but later version it are not working fine

### PR DESCRIPTION
**Pull request by cyBerta**
fixes #1525

### CODE REVIEW

**Comment by cyBerta** [comment]
info about grouping notifications and API version can be found here: https://developer.android.com/training/notify-user/group.html

**Comment by r10s** [comment]
great finding!

however, i do not really get why setGroup() causes an issue on API<24 - i though using the NotifcationCompat class just does "nothing" for older APIs not supporting some aspect.

**Comment by cyBerta** [comment]
> great finding!
> 
> however, i do not really get why setGroup() causes an issue on API<24 - i though using the NotifcationCompat class just does "nothing" for older APIs not supporting some aspect.

yeah, it NotifcationCompat _should_ handle these cases, but... notifications are a mess :D
I could both reproduce the bug without that change and see that it is fixed with that change.

**Review by r10s — APPROVED** [review]
great!

**Pull request merged**
