### PR TITLE
Create strings.xml

### PR DESCRIPTION
**Pull request by ngocanhtve**
Add Vietnamese language.

### CODE REVIEW

**Comment by r10s** [comment]
wow! thanks a lot! 🙏

i will push that with the iso-code `vi` directly to [transifex](https://delta.chat/en/contribute) (where future additions should take place then, you can log in there with your github handle, but as said, not needed just now)

@ngocanhtve the in-app language selector always shows the local name, wikipedia says the local name of the language is "tiếng Việt" - i would add that to https://github.com/deltachat/deltachat-android/blob/main/res/values/arrays.xml#L38 then

**Comment by ngocanhtve** [comment]
Thank you!

**Comment by r10s** [comment]
k, i did the changes at https://github.com/deltachat/deltachat-android/pull/2852

thanks again a lot for the complete (!) translation!

we have a small translators group, usually only few messages per week - in case you're using Delta Chat on your own, i can add you there (and if you do not use Delta Chat but want to, i can also help with a dedicated email address, just text me under &nbsp; _r10s &nbsp;AT&nbsp; b44t.com_ &nbsp; )

good timing btw, i was doing a release anyways just now :)

**Comment by ngocanhtve** [comment]
I'm using Delta Chat. My email is ngocanh.tve@gmail.com. Thank you.

**Pull request merged**
