### PR TITLE
changes for f-droid

### PR DESCRIPTION
**Pull request by r10s**
f-droid does not allow random maven urls, only the following whitelisted: https://gitlab.com/fdroid/fdroidserver/blob/master/fdroidserver/scanner.py#L98 - so we have to remove the dependencies from the signalapp maven repos.

the remaining maven repos are: 

- [x] https://github.com/chrisbanes/PhotoView - replaced by https://jitpack.io
- [x] https://github.com/leolin310148/ShortcutBadger - replaced by maven std. repo (whatever this is)
- [x] https://github.com/dmytrodanylyk/circular-progress-button - we do not really use them and i do not like them, replaced by <Button>

i have no idea why signal uses this from their own repos.

also, if someone know about how the dependecyVerification works, we  could re-add this. not sure if this is needed,  at least the used repos are whitelisted and under some control.

- [x] finally, there are some references to google-play, these could probably be removed

tackles #444

### CODE REVIEW

**Comment by angelo-fuchs** [comment]
jitpack is just a redirection to the signal codebase (afaics), not sure if this is an improvement.
We should probably find a way to remove the dependencies that come from this angle overall.
(continuing reviewing)

**Comment by angelo-fuchs** [comment]
Shortcut Badger: Do we use that? https://github.com/leolin310148/ShortcutBadger - At least on my phone nothing like that is shown. I recommend pruning completely (unless someone objects)

**Comment by angelo-fuchs** [comment]
PLAY_STORE_DISABLED should be removed completely from the code, not just the place where it might be set. (esp. as we don't actually use it)

**Comment by r10s** [comment]
> jitpack is just a redirection to the signal codebase (afaics), not sure if this is an improvement.

it's just that jitpack.io is whitelisted by f-droid. in general, i agree, in the mid-term, we should get rid of as many maven repos as possible.

**Comment by r10s** [comment]
> wrt PLAY_STORE_DISABLED [...]

k - i removed the comment and the surrounding dead code. the BuildConfig-thingie is just generated code. after a rebuild-all, it will be gone.

wrt issues - sure :)

**Pull request merged**
