### PR TITLE
display title bar and back button in welcome screen

### LINKED ISSUE #2870: add "close" button in the upper left corner of the welcome title bar
some people click "add new account" then don't know how to go back, or close the app and forget then opening again opens in welcome screen, and they think their accounts are lost

### PR DESCRIPTION
**Pull request by adbenitez**
close #2870

### CODE REVIEW

**Comment by r10s** [comment]
i think, we should differ between the mode of "very first startup" and "adding an account  later"

- on first startup, use the title "Welcome to Delta Chat" and do not show the "back" button (it is not needed, the fewer elements the better, ppl know how to exit an app, and we also did not had that before)

- later on, use "Add Account" as the title (so, same dialog title as the invoking button reads, this is always good style :)

**Comment by adbenitez** [comment]
> * and do not show the "back" button

this is already the case



> * on first startup, use the title "Welcome to Delta Chat"

done :+1:

**Comment by adbenitez** [comment]
btw later on we could consider now that we have a title bar, to also put a menu there, with things like a menu option to open the offline help and maybe a link to "online support" opening the forum, but IIRC at the moment it is not possible to open the offline help from this screen

**Comment by r10s** [comment]
> but IIRC at the moment it is not possible to open the offline help from this screen

yip, at some point we should streamline the two base classes to one and implement special activity redirecting for add-second-device- or welcome-activity over a flag

**Review by r10s — APPROVED** [review]
lgtm now, also tested a bit. thanks a lot!

**Pull request merged**
