### PR TITLE
use internal help instead of external links for "learn more" buttons

### LINKED ISSUE #2829: link "learn more" to the offline help
this should be done once the online help is "stable" and merged

### PR DESCRIPTION
**Pull request by adbenitez**
to test change the fragment/section to something like "#groups" since the linked sections don't exist yet in the offline help

close #2829

### CODE REVIEW

**Review by Hocuri — APPROVED** [review]
Code LGTM, didn't test. Nice!

This needs to wait for https://github.com/deltachat/deltachat-pages/pull/746 and then also update the help (I assume that that's what `scripts/create-local-help.sh` is for)

**Comment by r10s** [comment]
better remove the not-yet-existing links and leave only the existing `#multiclient`  fragment - maybe we will leave things online for first version of 1.42, this will give us a little more time to settle wording and translations; this is not decided yet

but we would be prepared and can test the in-app help already

**Review by r10s — CHANGES_REQUESTED** [review]
i wanted to get that in [1.41.7](https://github.com/deltachat/deltachat-android/pull/2850) (for general testing, without guaranteed-e2ee-urls)  -- however it crashed for me when trying to open from "Add Second Device / Troubleshooting" (sdk14, emulator)

**Comment by adbenitez** [comment]
> i wanted to get that in [1.41.7](https://github.com/deltachat/deltachat-android/pull/2850) (for general testing, without guaranteed-e2ee-urls) -- however it crashed for me when trying to open from "Add Second Device / Troubleshooting" (sdk14, emulator)

this is the error:

```
11-14 14:31:45.220 14425 14425 E AndroidRuntime: java.lang.RuntimeException: Unable to destroy activity {com.b44t.messenger.beta/org.thoughtcrime.securesms.LocalHelpActivity}: java.lang.NullPointerException: Attempt to invoke virtual me
thod 'void android.webkit.WebView.destroy()' on a null object reference                                                                                                                                                                     
11-14 14:31:45.220 14425 14425 E AndroidRuntime:        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5620)                                                                                                      
11-14 14:31:45.220 14425 14425 E AndroidRuntime:        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5653)                                                                                                       
11-14 14:31:45.220 14425 14425 E AndroidRuntime:        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)                                                                                           
11-14 14:31:45.220 14425 14425 E AndroidRuntime:        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)                                                                                   
11-14 14:31:45.220 14425 14425 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)                                                                            
11-14 14:31:45.220 14425 14425 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)                                                                                           
11-14 14:31:45.220 14425 14425 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2420)                                                                                                             
11-14 14:31:45.220 14425 14425 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)                                                                                                                             
11-14 14:31:45.220 14425 14425 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:211)                                                                                                                                      
11-14 14:31:45.220 14425 14425 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:300)                                                                                                                                          
11-14 14:31:45.220 14425 14425 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8227)                                                                                                                        
11-14 14:31:45.220 14425 14425 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)                                                                                                                                   
11-14 14:31:45.220 14425 14425 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)                                                                                                
11-14 14:31:45.220 14425 14425 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)                                                                                                                    
11-14 14:31:45.220 14425 14425 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.webkit.WebView.destroy()' on a null object reference
11-14 14:31:45.220 14425 14425 E AndroidRuntime:        at org.thoughtcrime.securesms.WebViewActivity.onDestroy(WebViewActivity.java:158)
11-14 14:31:45.220 14425 14425 E AndroidRuntime:        at android.app.Activity.performDestroy(Activity.java:8835)
11-14 14:31:45.220 14425 14425 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1472)
11-14 14:31:45.220 14425 14425 E AndroidRuntime:        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5607)
11-14 14:31:45.220 14425 14425 E AndroidRuntime:        ... 13 more
```

**Comment by adbenitez** [comment]
> i wanted to get that in [1.41.7](https://github.com/deltachat/deltachat-android/pull/2850) (for general testing, without guaranteed-e2ee-urls) -- however it crashed for me when trying to open from "Add Second Device / Troubleshooting" (sdk14, emulator)

I think the problem is related to PassphraseRequiredActionBarActivity class, when we are in "add second device" mode we don't allow opening any other activity and always point to the "add second device" screen because otherwise user will lose the current process, so delta is locked in this "add second device" screen no matters what you try to do or if you open the app from the launcher icon

so maybe we should leave the troubleshooting link external so it can be opened in the browser while the app remains in the add second device screen

**Comment by r10s** [comment]
wait: on the other hand, there is the "View Log" activity that can be used from "Add Second Device" activity - how is that different?

**Comment by adbenitez** [comment]
> wait: on the other hand, there is the "View Log" activity that can be used from "Add Second Device" activity - how is that different?

that is why LogViewActivity extends BaseActionBarActivity instead of PassphraseRequiredActionBarActivity, we can not do that for the WebviewActivity because it is used for html messages and webxdc apps that can be opened from home shortcut etc. 

we could make the Help activity extend BaseActionBarActivity directly and then duplicate the logic we currently use by extending WebviewActivity

**Comment by r10s** [comment]
thanks for investigation and explanation!

> we could make the Help activity extend BaseActionBarActivity directly and then duplicate the logic we currently use by extending WebviewActivity

nothing for now then :)

**Comment by r10s** [comment]
sooooo, if we get https://github.com/deltachat/deltachat-android/pull/2860 in:
-  revert the last commit of this pr (so that in-app-help is used for guaranteed e2ee)
- disable in-app-help for multiclient

**Comment by r10s** [comment]
thanks for reverting and adaptings the commits! i just force-pushed to get the new in-app help in ... testing now

**Review by r10s — APPROVED** [review]
lgtm, and also works as expected 👌

**Pull request merged**
