### PR TITLE
add 'learn more' to ephemeral messages dialog

### PR DESCRIPTION
**Pull request by r10s**
~~a help update to get https://github.com/deltachat/deltachat-pages/pull/765 in needs to be done before merging this makes sense.~~ ~~also, #2883 should be fixed before.~~ EDIT: both are done

however, it can already be approved :)

### CODE REVIEW

**Review by missytake — APPROVED** [review]
The #ephemeralmessages don't seem to be part of the help yet... but apart from that it seems to be fine.

**Comment by r10s** [comment]
> The #ephemeralmessages don't seem to be part of the help yet...

it was added recently, see https://github.com/deltachat/deltachat-android/blob/main/assets/help/en/help.html#L397

**Comment by missytake** [comment]
> > The #ephemeralmessages don't seem to be part of the help yet...
> 
> it was added recently, see https://github.com/deltachat/deltachat-android/blob/main/assets/help/en/help.html#L397

yeah, just not in the preview apk ;)

**Comment by r10s** [comment]
> yeah, just not in the preview apk ;)

ah :) i rebased the pr, in case you only want to see it, here is a screenshot:

**Review by missytake — APPROVED** [review]
Looks good now!

**Review by adbenitez — APPROVED** [review]

**Pull request merged**
