### PR TITLE
send images from 'Image keyboard' as stickers

### LINKED ISSUE #1945: send keyboard-stickers as such
many system keyboards these days have the option to select/handle stickers.

Delta Chat supports these stickers, however, they are sent as images and not as stickers.

we should change them to be sent out as DC_MSG_STICKER, esp. as all [UI display stickers nicely meanwhile](https://support.delta.chat/t/no-chat-bubble-with-stickers/412/9).

this is eg. how the sticker-selector looks on an motog with android7:

(original feature request in the forum at https://support.delta.chat/t/stickers-simplified/1708/4)

### PR DESCRIPTION
**Pull request by r10s**
see https://developer.android.com/guide/topics/text/image-keyboard

closes #1945

### CODE REVIEW

**Comment by adbenitez** [comment]
maybe for the future:

- if a quote-reply is stagged the sticker should reply the quoted message,
- draft should not be reused, just set the sticker to quote that message and remove the quote from the draft, preserving text or maybe it is also ok to discard the draft completely?

**Comment by adbenitez** [comment]
btw I am already using this, it works like a charm :D

**Comment by r10s** [comment]
> btw I am already using this, it works like a charm :D

great to hear that!

do you get these weird toasts as of https://github.com/deltachat/deltachat-android/issues/1948 ?

**Comment by r10s** [comment]
@adbenitez i added a commit that handles quotes as you suggested; see commit-message for details. i think, this or is now ready for review.

**Comment by adbenitez** [comment]
> do you get these weird toasts as of #1948 ?

no, with the stock Samsung keyboard and with AnySoftKeyboard it works fine

**Review by adbenitez — APPROVED** [review]
code lgtm, also tested it already with two keyboards for a while

**Pull request merged**
