### PR TITLE
use larger input-view and smaller chat-view

### PR DESCRIPTION
**Pull request by csb0730**
Extend size of message text input field from 4 to 10 lines max.

### CODE REVIEW

**Comment by csb0730** [comment]
This PR tackles #91

**Comment by r10s** [comment]
@csb0730 thanks for pushing this forward :)

some additional lines are welcome, however, the text input field should not be larger than, say, 50% of the available height so that the user can scroll around in the message list while typing.
not sure if this is achieved by this change.

this probably needs some testing on different devices.

as we plan a release this week, I would tend to merge this _after_ this release so that some larger testing "in the wild" can be done before.

**Comment by Ampli-fier** [comment]
I tested on my phone (larger display) and my personal feeling was that 10 is too much. 8 fits better.

**Comment by Ampli-fier** [comment]
Is it possible to have this field resizable? That the user can move the upper border to a preferred position?

**Comment by adbenitez** [comment]
Maybe not to have it resizable but alternating between the default mode and a fullscreen mode, where the text area fills the screen, may be easier and good enough

**Comment by r10s** [comment]
replaced by https://github.com/deltachat/deltachat-android/pull/976

**Pull request closed without merging**
