### PR TITLE
In direct sharing, propose only chats we can send to, fix #1274

### LINKED ISSUE #1274: Share with -> # crashes Delta Chat
- Android version: 7.1.2
- Device: MotoG3
- Delta Chat version: 1.3.0 (dev version)
- Actual behavior:
  In the "Direct share" section there appears a chat that has a white `#` on black background coming form Delta Chat. When I click it, DC crashes.
- Steps to reproduce the problem:
  - Click in "Share" in another app
- Logs:
```
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.b44t.messenger.beta/org.thoughtcrime.securesms.ConversationActivity}: java.lang.IllegalStateException: can't display a conversation for no chat.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2684)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6186)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
     Caused by: java.lang.IllegalStateException: can't display a conversation for no chat.
        at org.thoughtcrime.securesms.ConversationActivity.initializeResources(ConversationActivity.java:835)
        at org.thoughtcrime.securesms.ConversationActivity.onCreate(ConversationActivity.java:225)
        at org.thoughtcrime.securesms.PassphraseRequiredActionBarActivity.onCreate(PassphraseRequiredActionBarActivity.java:34)
        at android.app.Activity.performCreate(Activity.java:6684)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6186) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) 
```

I have no such chat in my chat list, no wonder DC crashes. But why does this icon appear?

### PR DESCRIPTION
**Pull request by Hocuri**
In direct sharing, propose only chats we can send to, fix #1274

### CODE REVIEW

**Comment by Hocuri** [comment]
@cyBerta Maybe you can also have a look here?

**Comment by r10s** [comment]
i just noticed that also the normal in-app forward-list shows the device-chat, i made a pr to fix that in the core, https://github.com/deltachat/deltachat-core-rust/pull/1367 - maybe we should also create the list here using the flag DC_GCL_FOR_FORWARDING on getChatlist() - however, the additional canSend() check here still makes sense imho and adds some resilience.

**Comment by Hocuri** [comment]
> i just noticed that also the normal in-app forward-list shows the device-chat

At least for Android, my PR already fixes this.

> i made a pr to fix that in the core, deltachat/deltachat-core-rust#1367 

Does the "Saved messages" chat stay? Because I think that it should.

> maybe we should also create the list here using the flags DC_GCL_FOR_FORWARDING|DC_GCL_NO_SPECIALS on getChatlist() - however, the additional canSend() check here still makes sense imho and adds some resilience.

Why not only check canSend()? Sounds reasonable that, we share exactly to those chats we can send to.

**Comment by cyBerta** [comment]
I agree with @r10s wrt. the flags. it would be nice to use `DC_GCL_FOR_FORWARDING|DC_GCL_NO_SPECIALS`. It would guarantee that the saved messages icon will always be present for direct sending and remove the contact requests as well as the archive entry from the list.

**Comment by cyBerta** [comment]
> Does the "Saved messages" chat stay? Because I think that it should.

yes

**Comment by Hocuri** [comment]
Ok, done.

**Pull request merged**
