### PR TITLE
Add "go to last seen"

### LINKED ISSUE #1528: Add "go to last seen"
- Operating System (Linux/Mac/Windows/iOS/Android): Android
- Delta Chat Version: Some versions or years ago (I don't know) until current master
- Expected behavior: When I open a chat with unread messages, I get to the position of the first unread message and a "3 unread messages" is shown
- Actual behavior: it is not shown
- Steps to reproduce the problem: Receive many messages (that do not fit on the screen) and open the chat

### PR DESCRIPTION
**Pull request by Hocuri**
Fix #1528

### CODE REVIEW

**Review by adbenitez — CHANGES_REQUESTED** [review]
the scroll to bottom button is displayed without the white circle background, to solve the issue, go to [on_scrolled](https://github.com/deltachat/deltachat-android/pull/1641/files#diff-69300c56791a105d9ac87d0eaca14044R580)

and replace with:
```
	    if (currentlyAtZoomScrollHeight && !wasAtZoomScrollHeight) {
                ViewUtil.animateIn(scrollToBottomButton, scrollButtonInAnimation);
            } else if (currentlyAtBottom && !wasAtBottom) {
                ViewUtil.animateOut(scrollToBottomButton, scrollButtonOutAnimation, View.INVISIBLE);
            }
```

the issue was that both "if" branches where executed, and somehow that messed the button.

**Comment by adbenitez** [comment]
also, if a new message arrives with the chat open, the marker disappears, would be nice if it works like the other marker(when screen goes off with chat open) and keeps increasing the counter "X new messages", but for a first implementation is good enough as is +1

**Comment by Hocuri** [comment]
@adb I addressed your change request, could you re-review?

**Comment by adb** [comment]
> @adb I addressed your change request, could you re-review?

@adbenitez ^

**Comment by Hocuri** [comment]
@adbenitez oops, I addressed it but forgot to push :1st_place_medal: :rofl:

**Review by adbenitez — APPROVED** [review]

**Pull request merged**
