### PR TITLE
strip release libraries

### PR DESCRIPTION
**Pull request by elwerene**
Add strip commands to strip libraries to save about (25% unzipped) 12% zipped in release apk

### CODE REVIEW

**Comment by Hocuri** [comment]
lgtm, @r10s in my opinion we can merge this.

**Comment by r10s** [comment]
it's maybe more complicated :) 

we decided in https://github.com/deltachat/deltachat-android/issues/1437 to  spend some extra mb to allow better debugging. the release script in tools/upload-release.sh uploads the symbols together with the apk to  https://download.delta.chat/android/

this way, when we get a crash,  ndk-stack should be able to replace the hex-numbers in an android-log by symbol-names and linenumbers. the thing is quite new, not sure if we ever made use of it.

so, i am wondering, if the armv7a-linux-androideabi-strip removed information we may need for making sense of logfiles.

**Comment by r10s** [comment]
@Hocuri @elwerene does building with this pr work on your machines?

i just tried on mac, 

- first i got an error `./ndk-make.sh: line 38: armv7a-linux-androideabi-strip: command not found` - so at least on mac, the strip is called `arm-linux-androideabi-strip` (without `v7a`)

- fixing that, strip runs through, however, finally i am getting a lot of "undefined reference" errors [[*]](https://gist.github.com/r10s/59ad60188a73d348b15868079999a6f6)

**Comment by elwerene** [comment]
I fixed the strip command. It was wrong on linux as well. I don't have any undefined reference errors.

**Comment by r10s** [comment]
hm, for me, on mac, still all dc_* references are missing, log: https://gist.github.com/r10s/a17e6cca3348133011c210d9faa3405b

**Comment by elwerene** [comment]
Oh nevermind, I just checked the output of ndk-build is stripped anyways. I used some rust on mobile before, but we didn't use ndk-build, we directly used the .so files produced by rust.
```
file libs/*/*.so
libs/arm64-v8a/libnative-utils.so:   ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), statically linked, BuildID[sha1]=4a07be890c0d578efbcec2d9a4b7b509b91f3fa0, stripped
libs/armeabi-v7a/libnative-utils.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), statically linked, BuildID[sha1]=cb181cc4f1e7ffc37cf3de1e9fd8bb5e4850fd2b, stripped
libs/x86_64/libnative-utils.so:      ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), statically linked, BuildID[sha1]=6a4c6f87a1c4a6907a7ca8454233865f674bdbf3, stripped
libs/x86/libnative-utils.so:         ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), statically linked, BuildID[sha1]=95a3b83b2038db3c920f47c4a52cd79358b532b2, stripped
```

**Pull request closed without merging**
