### PR TITLE
Fix emojis on android 4

### LINKED ISSUE #1493: No more emoji's on Android 4.1.2
- Operating System (Linux/Mac/Windows/iOS/Android):Android 4.1.2
- Delta Chat Version:1.10.4; 1.10.5 (nightly 2020-07-21)
- Expected behavior:Emojis are displayed
- Actual behavior:Emojis are not displayed
- Steps to reproduce the problem:Enter a chat and click the emoji  #icon.
Screenshot_2020-07-21-18-12-54

- Screenshots:

Regards Mike

### PR DESCRIPTION
**Pull request by cyBerta**
fixes #1493

I was able to reproduce the bug and indeed webp and vector graphics haven't been displayed correctly on Android API < 18

I converted all webp files to pngs and enabled a compat option to display vector graphics correctly on old devices. Vector graphics are used in the lower tabbar for the different emoji catergories. 

I tested on a Samsung Galaxy S Android 4.4 cyanogenmod and a Samsung Galaxy S4 mini, Android 9 (Lineage OS). I couldn't visueally recognize any difference performance wise between loading webps and pngs on the S4 mini.

### CODE REVIEW

**Comment by r10s** [comment]
good catch with the webp thingie!

unfortunately, this pr adds 12.4 mb to the apk (emojis 7.4 mb webp vs -19.8 mb png). wondering if that can be optimized somehow, i have the feeling a eg. 1024x1024 png with 1.6 mb (flags.png) is pretty big. maybe converting to 8bit optimized palette+dithering is worth a try.

wrt vector: so we can now savely use svg as https://github.com/deltachat/deltachat-android/pull/1480 - @cyBerta can you please double check that?

**Comment by r10s** [comment]
just tried a random png-minifier (https://tinypng.com)

original (629 kb):

Activity

minified (100kb, 84% saved):

Activity

if you enlarge the images, you will notice differences, the minified version uses 8bit-palette dithering instead of 24bit-true-color.

it would be great, if we can use a 12bit- or 16-bit-palette, i think, then nothing would be noticable and the saving would still be huge.

**Comment by cyBerta** [comment]
> wrt vector: so we can now savely use vectors as #1480 - @cyBerta can you please double check that?

Yes, the icon is visible using this PR on Android 4.4.

**Comment by link2xt** [comment]
Use [oxipng](https://github.com/shssoichiro/oxipng) on top of it for lossless compression. `cargo install oxipng`, then `oxipng -Z` for best compression (zopfli)

**Comment by Hocuri** [comment]
Why aren't we using jpg?
I could see a difference but not a lot, so I think that it's generally ok to show them this way.

**Comment by cyBerta** [comment]
I've used https://tinypng.com/ for compression. The results were visually better than with https://compresspng.com. But there are still some artifacts, you see it on the tennis ball for example.

Activity

**Comment by Simon-Laux** [comment]
And we can't use normal emoji fonts because older android has unicode bugs I assume?

**Comment by r10s** [comment]
yip, old androids have partly pretty poor emoji supports. 

wrt jpg: jpg does not offer an alpha channel. also, to achieve a comparable quality, jpg is probably not smaller as it is optimized for photos mainly.

**Comment by Simon-Laux** [comment]
> yip, old androids have partly pretty poor emoji supports.

Is the because the systems emoji font does not have the new characters or is that it also does not support new emoji fonts?

**Comment by r10s** [comment]
just a random issue, including an image of the missing emoji: https://github.com/deltachat/deltachat-android/issues/142 , there are lots more, just browser through older, fixes issues.

the example is maybe extreme, the gaps are smaller in newer androids, however still present, so sending from android 10 to an android 9 may result in missing emojis. i would also prefer to just use native emoji support, however, it does not seems reasonable currently.

**Comment by r10s** [comment]
@Simon-Laux back on-topic: do you see big/bad differences between the original imagses and the compressed on from @cyBerta? to me that looks pretty good! and we will save 18mb or so - so, a small regression seems to be reasonable :)

**Comment by Hocuri** [comment]
For saving 18mb, it is ok to use these emojis IMO.

**Comment by Simon-Laux** [comment]
@r10s I don't mean the system emoji font, we can ship an emoji font like we do in desktop. Question was if there is a fundamental problem with newer Unicode chars on older androids or if they are only missing on the systems font.

About the compression I don't care that much I'm having nothing against some retro looking dithering :smile:
:thinking: I think looking at this on a phone in a real chat makes more sense for comparing how it feels...

**Comment by r10s** [comment]
i think, we had all kind of problems with unicode and emojis on older androids, also, there is not "the" system's font, unfortunately :) for sure, there are several ways to solve them, due to the signal-codebase, we followed the png/webp way.

**Comment by AndreazLattmann** [comment]
You could use pngquant to reduce the size of the png files. 🤔

**Comment by r10s** [comment]
@AndreazLattmann there seems to be lots of tools - feel free to play around with them, and, if there is an even better solution, a pr is very welcome - coding is not required in this case, the challenge is just to get the png from this pr smaller an nicer :) (as original files, i would always use the webp, however)

**Comment by Simon-Laux** [comment]
We should try shipping the google noto color emoji font (https://github.com/googlefonts/noto-emoji) and see on android 4 if there are any bugs with it... do we have an android 4 device? who has one?

**Comment by Simon-Laux** [comment]
But on the other hand its fine for now, but if we can get the font somehow to work it I would vote for using a font instead of image files.

**Comment by Simon-Laux** [comment]
I think I found what we could use https://developer.android.com/guide/topics/ui/look-and-feel/emoji-compat

**Comment by link2xt** [comment]
> we could try https://developer.android.com/guide/topics/ui/look-and-feel/emoji-compat but that maybe depends on the playstore.

It depends on Android 4.4, and we support Android 4.1, and @adbenitez supports a build running on Android 4.0.

**Comment by Hocuri** [comment]
If we want to change the png pictures, then using the noto (https://github.com/googlefonts/noto-emoji) emojis might be an idea because they have fewer color gradients as far as I could see. And 1. it were the gradients that looked less good in the new emojis, 2. gradients make the images bigger.

**Comment by Oblivion94** [comment]
I think that Google Noto Font would be an excellent option for fonts, since it has support for the SVG format. That way, the emojis would scale correctly on all devices.
However, Google Noto Fonts has been outdated for some time. One option that is faithful to each version of Unicode and is also Open source is Twitter's twi-emoji.
https://github.com/twitter/twemoji

**Comment by Hocuri** [comment]
Yes, Twemoji seems to be a better choice, then, because they have few gradients, too.

**Comment by Simon-Laux** [comment]
@Oblivion94 what is outdated at gogle noto? (besides the font they offer on the download page?)

**Comment by Oblivion94** [comment]
@Simon-Laux Noto Color Emoji is a very cool font, but according to its official page it was only updated to Unicode version 10
https://www.google.com/get/noto/help/emoji/

For this reason many emojis are lost along the way.
However twi-emoji is constantly updated to new Unicode versions, currently 13
https://twemoji.twitter.com

From the Github page you can see the changelog
https://github.com/twitter/twemoji/releases

In addition, as well @Hocuri has less color gradients and is very simple.

**Comment by Simon-Laux** [comment]
@Oblivion94 as I mentioned the website of noto is outdated, the github page has the emojis for version 13 (updated 5 days ago)
From what I saw noto reduced its gradients a bit.

I couldn't find the font file for Twemoji. though I have no opnion on whether we should or shouldn't use it.

Openmoji would also be an option but the style is rather unique which could be unfamiliar for users, they work on implementing version 13 too (https://github.com/hfg-gmuend/openmoji/issues/124)

**Comment by Oblivion94** [comment]
@Simon-Laux I see, Noto also updated to Unicode 13 recently. Honestly it is a matter that deserves a survey. I opt for Twitter due to the support and the active community they have.
A while back I discussed just these three options in the support forum:
https://support.delta.chat/t/more-modern-and-vector-format-emojis-svg/851
It is the most convenient type of format for emojis for several reasons. Hopefully you decide to implement it in the next versions :)

**Comment by icke68746** [comment]
Operating System (Linux/Mac/Windows/iOS/Android):Android 4.1.2
Since tonight's version (deltachat-gplay-debug-1.11.0.apk 26-Jul-2020 00:38 68830441), the emojis are back. Thanks!
Screenshot_2020-07-26-15-33-20
Regards Mike

**Comment by r10s** [comment]
thanks for confirming, @icke68746 :)

**Pull request merged**
