### PR TITLE
move pref_system_emoji pref to advanced and enable it by default

### LINKED ISSUE #2980: tune down in-app emoji selector
the in-app emoji selector is worse than what most modern keyboards offer wrt emoji, eg ...

- modern emoji
- stickers

... are available by many keyboards - but not by our in-app emoji selector.

the last update was several years ago, it seems, we cannot really maintain that effort, even if we based on existing upstream (which does not supported older android ...). also, it seems unnecessary as things are already offered by keyboards - and our limited resources are better spent elsewhere.

to move forward on this issue, get some feedback and to not annoy existing users too much, we could do the following:

1. let `pref_system_emoji` default to `true` for new installations (existing installation stay as is for now)
2. move option "Appearance / Use System Emoji" to "Advanced / Use In-App Emoji" with the subtitle "In-app emoji often has less features" (just beside "Use In-App Camera")

then, let's see what happens :)

as a successor, we could check out [EmojiCompat](https://developer.android.com/reference/androidx/emoji/text/EmojiCompat) and see if that can replace emojify() & co. but that can come later as needed and would require are larger cleanup.

@adbenitez @all or do newer androids with really worser-than-our emoji-picker exist? all i have seen recently on androids was way better, even the default stock-androids in the emulators

### PR DESCRIPTION
**Pull request by adbenitez**
close #2980

### CODE REVIEW

**Comment by r10s** [comment]
hm, better go on pair with "in-app camera" and name the option "User In-App Emoji" as well (inverted then), see https://github.com/deltachat/deltachat-android/issues/2980 - i would also define new strings for that, reusing with changed meanings will add some noise to translators.

so, `pref_use_builtin_emoji` and `pref_use_builtin_emoji_explain`, comparable to https://github.com/deltachat/deltachat-android/pull/2674/files

**Comment by adbenitez** [comment]
(notice this PR changes the default to prefer system emoji for all DC users not only new ones, I was not sure how to detect this, but also I think it should be fine to change for all, they can always enable them again in the settings)

**Comment by r10s** [comment]
yeah, wording looks lice now. thanks!

> (notice this PR changes the default to prefer system emoji for all DC users not only new ones, I was not sure how to detect this

i would not try to detect it, but just continue us

> but also I think it should be fine to change for all, they can always enable them again in the settings)



while it is true that ppl can switch 
hm, but we will need to deal with requests and discussions then. i wo

**Comment by r10s** [comment]
sorry for closing and adding noise /me cannot type on the phone today ...

**Comment by adbenitez** [comment]
> i would not try to detect it, but just continue using the old flag.

since old flag was for "use system emoji" and it was disabled by default, there is no old key value saved, so you can't know if the key is not set because it is a new user or because it is an old user that never changed the setting and hence was using built-in emoji :thinking:

**Comment by adbenitez** [comment]
closing this PR, see https://github.com/deltachat/deltachat-android/issues/2980#issuecomment-2252706584 for the reasoning

**Pull request closed without merging**
