### PR TITLE
show system message status while sending and on errors

### LINKED ISSUE #1880: message sending status is unknown for system messages
when you add/remove a member of the group, or generate another kind of system message, the status of the message is unknown, you can't know easily if the message was delivered or failed.

Delta Chat Desktop already solved this showing the spinning wheel when the message is being sent and hiding it when it is sent.

### PR DESCRIPTION
**Pull request by adbenitez**
close #1880

### CODE REVIEW

**Comment by Hocuri** [comment]
Nice! 

Small thing: if the system message failed, you can't tap on it to get the error message, and the error symbol is not drawn in red. (both as opposed to normal messages)

Doesn't have to be now, though, this PR is definitely an improvement already.

**Comment by adbenitez** [comment]
@Hocuri I plan to add the "click to see error" while I am at #1882 that will add the click event handler for system messages, to handle click on errors and in contact request view,

about the red color, I don't know how to get the text color in this part of the code, if you can give me a tip :D

**Comment by adbenitez** [comment]
(I need to set it to RED or restore to text color because the item could be recycled and get a red spinner etc)

**Comment by Hocuri** [comment]
Maybe this helps: https://github.com/deltachat/deltachat-android/pull/1752/files#diff-373c1c336fc93cb63793425211d1bb1a523dfac44f6a27f6e88e4cb670eaf03f

**Comment by adbenitez** [comment]
yes, I am working on it already thanks!

**Comment by adbenitez** [comment]
done, when this is reviewed and merged I then will work add the click part while working on #1882

**Review by Hocuri — APPROVED** [review]

**Pull request merged**
