### PR TITLE
Wider messages for tall images

### PR DESCRIPTION
**Pull request by Hocuri**
Fix https://github.com/deltachat/deltachat-android/issues/1687

Don't know if such a change should wait until after the release because a bug could be introduced?

Screenshot_20201025-163623
Screenshot_20201025-163611
Screenshot_20201025-163550
Screenshot_20201025-163543

### CODE REVIEW

**Comment by r10s** [comment]
> Don't know if such a change should wait until after the release because a bug could be introduced?

i'll have a look :)

thanks a lot for pushing that forward, this is a personally long-awaited fix :)

**Review by r10s — CHANGES_REQUESTED** [review]
i did not look that much at the code but tested the pr more in practice with groups i have on my phone :)

- we should not cut _landscape_ images, they can easily be shown in complete width as before

- we should cut _portrait_ images a bit less, so that the result is a _square_. this is less surprisingly when the image is enlarged and the user has a clue that this is not a _landscape_ image

both cases are also handled by whatsapp/etc in this way.

wrt merging: i would do that after the 1.14 release to allow testing that a bit more.

**Comment by Hocuri** [comment]
> * we should not cut _landscape_ images, they can easily be shown in complete width as before

Was a bug, I meant to make a minimum height but I wanted it to be 50dp, not 100dp (before there also was some limit on how low the height can get and I don' think we should change this)
> * we should cut _portrait_ images a bit less, so that the result is a _square_. this is less surprisingly when the image is enlarged and the user has a clue that this is not a _landscape_ image

That's a little harder to do, as: If the screen is in landscape and we show the image as a square then it will be easily twice as high as the screen and the image does not even fit on the screen. Maybe I'll just cut the image as I am currently doing but only while the device is in landscape mode (which should be the minority of cases by far, anyway)

**Comment by r10s** [comment]
> If the screen is in landscape and we show the image as a square then it will be easily twice as high as the screen and the image does not even fit on the screen.

that's a point.

i can imagine two solutions for that:
1. show portrait images cutted to landscape (as now), use square only if the whole device is in portrait mode
2. do not use the full width for the bubbles (for the text) in device-landscape-mode - this way, also the squares will maybe be small enough. at a first glance this is what whatsapp is doing

but yip, this is not super-urgent to decide, we will do the next release without this pr anyway.

**Comment by Hocuri** [comment]
> 1. show portrait images cutted to landscape (as now), use square only if the whole device is in portrait mode
> 
> 2. do not use the full width for the bubbles (for the text) in device-landscape-mode - this way, also the squares will maybe be small enough. at a first glance this is what whatsapp is doing

Actually, let's just do 1 if the text is longer than, like, 200 chars, 2 otherwise

**Comment by Hocuri** [comment]
> Actually, let's just do 1 if the text is longer than, like, 200 chars, 2 otherwise

Actually actually, 2 would be quite some work to implement and I don't think it's worth it. Currently I only implemented 1.

**Comment by Hocuri** [comment]
@r10s what about merging this now?

**Review by r10s — APPROVED** [review]
lgtm now - and yes, a good time for merging :)

**Pull request merged**
