### PR TITLE
allow to clone groups and broadcasts

### LINKED ISSUE #2786: add "clone group"
cloning group offers a pragmatic way to add unverified ppl to verified groups or upgrade to verified groups.

also the "birthday issue", where a 30 ppl group wants to discuss a present for one member is fixed by that.

no need to put the option too much in the way, however. the kebab menu in the group-profile will do. when tapped, the current group is left (pop 2 activities or so) and "new group" is opened with a prefilled member list and prefilled name (maybe appended by "Clone"?)

### PR DESCRIPTION
**Pull request by adbenitez**
close #2786 

this allows to upgrade existing non-verified groups to verified  by drafting a new group and then getting the chance to make it verified if all contacts are verified, thanks to recent changes in the group creation workflow

### CODE REVIEW

**Comment by adbenitez** [comment]
I made it possible to clone broadcast lists as well because it can be also useful now that they appear as a new chat/channel, so it can be used for new thread/topic announcements

I tried to keep it simple with the string and just say "clone" so it fits for both groups and broadcasts, it probably is nicer to be more specific and say "clone group"/"clone broadcast list"

also the name "clone" is a bit misleading here, you are not cloning the group with name and image, but drafting a new from an existing memberlist

**Comment by Hocuri** [comment]
> also the name "clone" is a bit misleading here, you are not cloning the group with name and image, but drafting a new from an existing memberlist, maybe the existing "new group"/"new broadcast" strings could be reused? starting a new group from an existing one is more in line with what is happening than "clone"

Well if we want we can also pre-fill the name and image with the ones from the previous group. Esp. setting the image could be useful since for the user it's not straightforward how to reuse the image from the old group (while they can just type in the same name if they want to reuse the name).

In any case, I think "clone" is better than "New group".

**Comment by adbenitez** [comment]
> Well if we want we can also pre-fill the name and image with the ones from the previous group

done :heavy_check_mark:

**Review by r10s — APPROVED** [review]
nice 👌

**Pull request merged**
