### PR TITLE
Notification clickable

### PR DESCRIPTION
**Pull request by Ampli-fier**
Click on Notification opens Delta Chat

### CODE REVIEW

**Comment by r10s** [comment]
Cool :) 
This give the notification more sense.
Have you tested that not multiple Delta activities laying over each other when clicking on the notification while Delta is already in foreground? (I had such stuff here and there, always with unexpected results when hitting the back-button) (not saying that this also happens for this PR :)

**Comment by r10s** [comment]
btw: we have basic Python bindings now :) see https://github.com/deltachat/deltachat-core/pull/83 :)

**Comment by Ampli-fier** [comment]
I do not see more than one instance when I test this. Going back works as expected and also the "app history" only shows one instance. I think the LaunchActivity is also started when one clicks on the DC icon. At least this was my intention.

I do not know what _Python bindings_ are. But I hope I will get to know it soon :)

**Comment by r10s** [comment]
Okay, then I will merge now :)

**Comment by r10s** [comment]
Just tested it on my device: Works like a charm!

**Pull request merged**
