### PR TITLE
set background image for QrShowFragment

### PR DESCRIPTION
**Pull request by adbenitez**
the current "QR Show" fragment looks a bit ugly/empty with the white background, this PR sets the nicer default chat background

### CODE REVIEW

**Comment by r10s** [comment]
a matter of taste a bit, but yes, more fancy  💅 i think, i like it :)

for dark theme, did you consider to use the dark default background?

ftr, this is how it looks like:

Screenshot 2023-03-14 at 12 11 13

**Comment by WofWca** [comment]
> for dark theme, did you consider to use the dark default background?

Be aware that some QR readers don't recognize inverted-color QRs. See, for example, https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/41049

**Comment by r10s** [comment]
> Be aware that some QR readers don't recognize inverted-color QRs. See, for example, https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/41049

yip, we are aware of that, the QR code is not changed and stays black on white, including a white border. it is only about the background image, that also exist in a dark variant

**Comment by adbenitez** [comment]
> for dark theme, did you consider to use the dark default background?

it automatically changes to the dark background, we use these special android folders that automatically selects the right background for light/dark modes and device orientation

**Comment by r10s** [comment]
this seems not to be sufficient. i could not manage to see the background in dark mode - neither by an os supporting darkmode nor by switching manually. the chat-background, however, follows all these modes, so we should probably peed what is done there.

**Comment by adbenitez** [comment]
@r10s mmmh, odd, in my phone it works even with the QrShowFragment in display, buy I think I know what is the difference: `DynamicTheme` but it is hard for me to fix if it is not broken in my device :/

**Comment by r10s** [comment]
i can have a look at that at some later point

**Comment by adbenitez** [comment]
never mind, it turned out that the folder stuff I mentioned earlier I did it in DeltaLab :man_facepalming:  so in official DC it is still the old way setting background_hd_dark manually, will push a fix

**Review by r10s — APPROVED** [review]
lgtm now

**Pull request merged**
