### PR TITLE
update welcome message

### LINKED ISSUE #2914: focus on setting up contacts in initial device message
the "device messages" chat is one of the few things that are present after "instant onboarding" (eg. via QR code scan on https://nine.testrun.org, maybe later in-app)

currently, the "welcome" messages shows some general hints, idea is to write down the most interesting thing for new users, how to get in contact with others (that are maybe sitting just next to me) - so, eg. 
- an image of two phones scanning each others QR code (needs to be changed in core iirc)
- a describing text about how to scan QR codes (cmp. [desktop/#3623](https://github.com/deltachat/deltachat-desktop/issues/3623) wrt streamlining) (can be changed on android)
- maybe show own QR code in device messages and/or allow opening the corresponding dialog via a tap/link
- to reduce noise in device chat, it is also questionable to show the "Changelog" also on initial installations (on real updates, however, it is cool)

desktop already opens the "device messages" after installations, so that should be mostly fine.
for android/ios, there is the additional idea to use space on the chatlist for additional hints, but i'd say, this is another issue, and it also depends on how good the updated device message already works (would be nice, if eg. already in the chatlist the summary "How to get in contact ... " or so is shown) 

(once this is settled here and in core, we have to check if desktop/ios needs adaptions or if just strings/core is updated)

current, a bit outdated device message:

nb: maybe the name "Device Messages" is also a bit cumbersome and buerocratic and sth. as "Hints" or "Notes" or just "Info" is better

### PR DESCRIPTION
**Pull request by r10s**
this PR 

1. updates the "welcome" message, making it more useful and explaining how to get in contact.

2. the "Get in contact" summary is already visible in the chat list, before the device message is opened

3. the idea is to replace the image as well, showing two devices scanning each other, sth as ... <br><br> ... but that needs to be done in core

for now, some of the old "advertisements" (advantages of delta chat) in the second part.

 

<details>
<summary>experiment: title changed to "Info"</summary>
we can still do this, however, better in another PR; also this may require more changes in help etc., so might be not that easy as just one line change :) (as always :)

 
</details>

closes #2914

### CODE REVIEW

**Review by adbenitez — APPROVED** [review]
much more useful message, maybe also point to the get.delta.chat page like the older message, "if your friends don't have delta chat or an email account yet, point them to ..."

**Comment by adbenitez** [comment]
about renaming from device messages to info, I am +/-0, maybe a bit + than -, but I guess this also requires changes FAQ/help and shouldn't it be named by core?

**Comment by Simon-Laux** [comment]
We probably need some special welcome message for chatmail explaining the limitations. or at least a special message / error when an unencrypted mail is rejected by a chatmail server.

**Comment by r10s** [comment]
> or at least a special message / error when an unencrypted mail is rejected by a chatmail server.

see https://github.com/deltachat/deltachat-core-rust/issues/5161 

> overlooked it [renaming "Device Messages" to "Info"] is just an experiment :)

i reverted the change, better to discuss that separately

**Review by adzialocha — CHANGES_REQUESTED** [review]
Yes, much better!

Small english grammar finding, shouldn't it be?

> Enjoy your messenger experience over the largest decentralized network **that** ever existed:

Otherwise all good

**Pull request merged**
