### PR TITLE
allow to export all selected attachments

### PR DESCRIPTION
**Pull request by adbenitez**
when selecting multiple messages that contain attachments, for example documents in the "Documents" tab, it was not possible to export all the selected attachments at the same time, user had to select & export one by one, this PR fixes this, allowing to export all selected messages if all of them have attachments

### CODE REVIEW

**Comment by adbenitez** [comment]
maybe also the string `R.string.ask_export_attachment` needs to be tweaked, for example, removing the start of the message "Export attachment?" or replacing with something like "Export attachment(s)?"

**Comment by r10s** [comment]
great!

> maybe also the string R.string.ask_export_attachment needs to be tweaked, for example, removing the start of the message "Export attachment?" or replacing with something like "Export attachment(s)?"

i'd add a new string "Export attachment**s**" (this is similar to delete and forward then) and remove the  start of the message "Export attachment?" as you suggested.

**Comment by adbenitez** [comment]
>     * for the menu entry, i'd add a new string "Export attachment**s**" (this is similar to delete and forward then)

I checked and it seems that "Forward message" is always used even if several messages are selected (not noticeable since a forward icon is used instead of the text

**Comment by adbenitez** [comment]
I tackled the missing parts

**Review by r10s — APPROVED** [review]

**Comment by r10s** [comment]
works like a charm, thanks a lot for taking care!

**Pull request merged**
