### PR TITLE
CI: fix and improve apk preview workflows

### PR DESCRIPTION
**Pull request by adbenitez**
remove deprecated action and make the generated APK more visible

### CODE REVIEW

**Review by r10s — APPROVED** [review]
great, thanks for taking care!

btw, i am always failing in finding the "apk artifact" for downloading, probably because i usually do not need it - however, is that only me? :)

**Comment by adbenitez** [comment]
indeed I no longer find the menu that was there in the past to download the artifact, the artifact is uploaded but it seems GitHub UI changed :v I think desktop puts the files directly in the PR somehow I will check that, otherwise it is too hard to find the artifact (well it was in the past now it is completely missing XD)

**Comment by adbenitez** [comment]
ah deltachat-desktop uploads stuff to https://download.delta.chat/desktop/preview/

**Comment by adbenitez** [comment]
found the artifact here at the end: https://github.com/deltachat/deltachat-android/actions/runs/1454807233

also if you remove the `?check_suite_focus=true` from the "Details" link the artifact menu then re-appears, that is pretty weird from GitHub:
 https://github.com/deltachat/deltachat-android/runs/4194649464

**Comment by r10s** [comment]
thanks for figuring that out! easy, when one knows where to search it :)

**Comment by adbenitez** [comment]
@r10s now the apk direct download link will be published in a comment in the corresponding PR, similar to what https://github.com/deltachat/deltachat-pages/ does with the pages previews. 

the nice thing is that people watching this repo will even receive the comment by email and can try the apk direclty without having to search here in GitHub

**Review by r10s — APPROVED** [review]
a post with a preview link sounds great!

**Review by Hocuri — APPROVED** [review]
Nice!

**Pull request merged**
