### PR TITLE
don't increase reaction selector's font size according to system

### LINKED ISSUE #3291: Bigger Android font and display sizes cause truncated reaction bar
- Android version:
Android 13 & 14.

- Devices:
Google Pixel 8 & Samsung Galaxy A71.

- Delta Chat version:
1.46.13.

- Expected behavior:
The reaction bar is not truncated when the sizes for font and display in Android are set to high levels.

- Actual behavior:
The reaction bar is truncated when the sizes for font and display in Android are set to high levels.

- Steps to reproduce the problem:
-- Set the sizes for font and display in Android to high levels.
-- Open a chat and long-tap a message you would like to react to. (Result: The reaction bar is truncated, the three-dot icon on the right is invisible and cannot be selected.)

- Screenshot:
grafik

- Logs:
N/A.

### PR DESCRIPTION
**Pull request by adbenitez**
also avoid moving the selector horizontally out of screen 

close #3291

### CODE REVIEW

**Review by r10s — APPROVED** [review]
good and easy fix 👍

**Review by Hocuri — APPROVED** [review]
It's not working when the screen is actually small or when the display size is increased in the settings (only when the font size is increased in the settings). Nonetheless, it's an improvement to how it is today.
Screenshot_20241112-142150

**Comment by adbenitez** [comment]
> It's not working when the screen is actually small or when the display size is increased in the settings (only when the font size is increased in the settings). Nonetheless, it's an improvement to how it is today.

mmmh weird, it should span to the full screen size but it is smaller for you, I tested with both, font and screen amplification and it looked fine for me :(

**Comment by Hocuri** [comment]
> could you try with system emojis?

I tried with current main (which has both this PR and https://github.com/deltachat/deltachat-android/pull/3411/ merged), still too big

**Comment by r10s** [comment]
seem the screen of @Hocuri is even smaller than the one in the original post - see the whitespace between "1" and "reply".

i fear, we need to be a little more adaptive here. maybe the following is good enough:

```
if screenWidth < N {
  set laugh-emoji and sad-emoji to View.GONE - maybe even heart-emoji
}
```

we were considering to hide sad-emoji alltogether, but that may not fix the issue accodingly, also for consistency with desktop (and also iOS has these emojis prefilled in the selector) that would not be a very nice solution

**Comment by adbenitez** [comment]
notice that the selector looks fine in hocuri is phone, it is about the case when in such small screen you also use the screen scaling/augmentation which is not what  someone with such small screen would do,

a more generic solution could be to use a scrollbar inside the bubble to catch such extreme cases at least without errors

**Pull request merged**
