### PR TITLE
More videochat footer padding

### LINKED ISSUE #2319: Horizontal padding values of transparent footer too low
- Android version:
Android 11.

- Device:
Fairphone FP2 (Lineage OS 18.1 build RQ3A.211001.001 from 2022-06-10).

- Delta Chat version:
1.30.3 (current nightly build).

- Expected behavior:
The horizontal alignment of the transparent footer is like for other footers which are not transparent.

- Actual behavior:
The horizontal alignment of the transparent footer is not like for other footers which are not transparent.

- Steps to reproduce the problem:
-- Receive a message that includes a transparent footer and compare it to the other ones which are non-transparent.

- Screenshots:
grafik
(The vertical line shall visualize the alignment.)

- Logs:
N/A.

### PR DESCRIPTION
**Pull request by Hocuri**
fix #2319

This is what it looks like now:

Screenshot_2022-07-09_18-34-48

### CODE REVIEW

**Review by r10s — APPROVED** [review]

**Review by adbenitez — APPROVED** [review]
nice!

**Review by gerryfrancis — APPROVED** [review]
I did not expect this minor issue to be fixed that soon, considering that there are much more important things to do. Works as expected, thank you so much, guys! :)

**Comment by Hocuri** [comment]
I mean, it was easier to fix than the more important things, just two lines :)

**Comment by Hocuri** [comment]
I guess that it's on @r10s to decide what gets merged right now vs. after the release?

**Pull request merged**
