### PR TITLE
Introduce dedicated ConversationListRelayingActivity to fix forwarding bug

### PR DESCRIPTION
**Pull request by Hocuri**
fix https://github.com/deltachat/deltachat-android/issues/1704 by creating an extra activity:

https://github.com/deltachat/deltachat-android/pull/2246/files#diff-5027fc167512e95578b7074b02d0740011435b3d033a2fe66d4893a74d81e0e2R12-R24

Also create some new UI test (and test it with the old UI tests) because we had so many regressions wrt sharing, forwarding and switching activities in the past. The test depends on https://github.com/deltachat/deltachat-core-rust/pull/3150; if it doesn't get merged, I'll have to find another method to disable this animation.

### CODE REVIEW

**Review by adbenitez — APPROVED** [review]
works like a charm, thanks a lot!!!!

**Review by r10s — APPROVED** [review]
let's merge that in soon, so we can find and target potential issues soon as well (seems unlikely, however, as the pr introduces a new activity just for forwarding and does not change existing activity flow imu)

**Comment by Hocuri** [comment]
I must ask, though, what does "imu" mean?

**Comment by r10s** [comment]
> I must ask, though, what does "imu" mean?

"in my understanding"

or "in my opinion" with a typo :)

**Pull request merged**
