### PR TITLE
Enhance log with scroll and zoom possibility

### PR DESCRIPTION
**Pull request by Ampli-fier**
targeting issue #857

### CODE REVIEW

**Comment by cyBerta** [comment]
Ok! Please take care of code style. The parameter  '`Textsize` https://github.com/deltachat/deltachat-android/pull/876/files#diff-c078e9def6523b1b486451c194dca7f8R90' should be in camel case and begin with a small letter. I'm going to merge it anyway for now.

**Comment by csb0730** [comment]
@cyBerta @Ampli-fier 
Would it be possible to add a menu item for logview to store current log to a file? Standard file name?
This would help very much.

**Comment by r10s** [comment]
@csb0730 yip, that would be helpful. maybe you can do a pr for that?

**Comment by Ampli-fier** [comment]
I'm going to start working on this the next days ...

**Pull request merged**
