### PR TITLE
Added border definitions to preference divider

### PR DESCRIPTION
**Pull request by Ampli-fier**
Added border definitions to the dark and light preference divider.
Changed the background color for the dark divider.

### CODE REVIEW

**Comment by cyBerta** [comment]
Hi Amplifier, is this PR referring to any issue ticket?

**Comment by Ampli-fier** [comment]
Hi @cyBerta 

No (issue written), this is just a minor alignment between the dark and light mode.

**Comment by r10s** [comment]
i think, this should be tested with android4 as well, iirc, there were some issues with ´<shape>´ and ´<solid>´ there; however, maybe @cyBerta has already :)

**Comment by Ampli-fier** [comment]
There are issues label'ed with _Android4_ (really helpful).

Searching for **solid** brings [one result](https://github.com/deltachat/deltachat-android/issues?utf8=%E2%9C%93&q=label%3Aandroid4+solid), searching for **shape** does not. The one result is about 'Using attr for parameters of drawables ...'

I installed the app on Android 4.4 and I get what is intended. There is no crash.

**Comment by cyBerta** [comment]
I've tested the PR with API 16

**Comment by r10s** [comment]
cool, thanks for testing :)

**Pull request merged**
