### PR TITLE
Oops, add missing attribute

### PR DESCRIPTION
**Pull request by Hocuri**
Follow-up for https://github.com/deltachat/deltachat-android/pull/2458

### CODE REVIEW

**Review by r10s — APPROVED** [review]

**Review by WofWca — CHANGES_REQUESTED** [review]
This isn't gonna work either, because `contentWindow.RTCPeerConnection` is always inaccessible for sandboxed iframes. Need to run the script _inside_ the iframe.

**Comment by Hocuri** [comment]
Can you send a patch that does this? I know nearly nothing about JavaScript/HTML.

**Comment by WofWca** [comment]
Ok, I'll sketch it up, and let you polish, cause I'm not good at mobile dev 😃

**Comment by WofWca** [comment]
I've shared the patch in the chat.

**Comment by r10s** [comment]
the patch is applied to https://github.com/deltachat/deltachat-android/pull/2465, @Hocuri @WofWca please double-check :)

**Pull request closed without merging**
