### PR TITLE
prepare version 1.6

### PR DESCRIPTION
**Pull request by r10s**
screenshot of the device message:

Screen Shot 2020-04-29 at 18 58 40

### CODE REVIEW

**Comment by r10s** [comment]
updated text, with reversed argumentation order:

Screen Shot 2020-04-30 at 10 53 40

**Comment by webratte** [comment]
Did you checked my posting in the testers group before you release the next version?

I believe there is a really problem with gmx and probably also web.de

**Comment by r10s** [comment]
yip, i've seen that. but it was a combined thing, so can you please double check that it is really a gmx issue? maybe with a fresh account? i also pinged @Hocuri in the testing group, however.

but anyway, we will not upload the version to the app stores today.

**Comment by Hocuri** [comment]
@webratte I could send and receive messages with about 5 seconds lag and the messages were moved to the "DeltaChat" folder (note that this was not a new account, though, but an old one that I did not need anymore)

**Comment by webratte** [comment]
Have you installed the newest version over this where the gmx Account was used?
Or did you started from the scratch and start with "login to your server"?

**Comment by webratte** [comment]
The biggest problem (for me) seems to be do not start from the scratch but install over a existing setup (or use a backup)

But the same problem happens if I send messages via OX-Coi (latest play store version) to the newest nightly. (gmx to gmx).

I can see all messages in OX-Coi.
But nothing in DC nightly.

All messages in the inbox. So gmx received all messages.

**Comment by Simon-Laux** [comment]
OX-Coi is incompatible with deltachat, because they changed how the message id is generated.

**Comment by webratte** [comment]
To bad. I hoped we get compatible clients as much as possible.

But there is still the problem between old and new core.
I have written to the other devs in german because what I (probably) find out is much to complex for me to describe it in englisch 😉

**Comment by webratte** [comment]
BTW:

OX Coi (current play store version) and DC (also current play store version) works fine together.

**Comment by webratte** [comment]
Sorry, your right.
OX Coi messages will not shown in DC.

I will open a issue infor OX Coi

**Comment by Hocuri** [comment]
> The biggest problem (for me) seems to be do not start from the scratch but install over a existing setup (or use a backup)

Yesterday I started over from scratch but now I tried to install a new release over existing setup and again, messages arrived.

**Comment by webratte** [comment]
On both sides GMX?

**Comment by Hocuri** [comment]
Ok, I now have Delta Chat 1.6 on two phones, one migrated, one new, on both I switched accounts a little in the meantime. (just in case this turns out to make a difference)

I do get all messages but **I do not get any notifications with 1.6**. With the old version (I installed it via F-Droid) everything is fine again (with a third GMX account). (actually confusing, we 

But the missing notifications seem not to have anything to do with GMX, this problem also exists in a Testrun-Testrun chat.

Log excerpt:
```
2020-05-01 10:39:34.494 469-469/? I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2020-05-01 10:39:37.510 469-469/? I/chatty: uid=1000(system) /system/bin/surfaceflinger identical 20 lines
2020-05-01 10:39:37.511 469-469/? I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2020-05-01 10:39:37.793 25400-25693/? I/DeltaChat: ThreadId(47) src/imap/idle.rs:94: Idle has NewData
2020-05-01 10:39:37.900 25400-25693/? I/DeltaChat: ThreadId(47) src/job_thread.rs:179: MVBOX-IDLE ended...
2020-05-01 10:39:37.905 25400-25693/? I/DeltaChat: ThreadId(47) src/job.rs:1038: dc_perform_mbox_jobs EMPTY (for now).
2020-05-01 10:39:37.907 25400-25693/? I/DeltaChat: ThreadId(47) src/job_thread.rs:105: MVBOX-fetch started...
2020-05-01 10:39:37.916 28430-28430/? W/qcom-system-dae: type=1400 audit(0.0:12686): avc: denied { read write } for name="diag" dev="tmpfs" ino=17517 scontext=u:r:vendor_qcomsysd:s0 tcontext=u:object_r:diag_device:s0 tclass=chr_file permissive=0
2020-05-01 10:39:37.928 28430-28430/? E/QCOMSysDaemon: Can't find/open bootselect node: (No such file or directory)
2020-05-01 10:39:37.928 28430-28430/? I/QCOMSysDaemon: Starting qcom system daemon
2020-05-01 10:39:37.928 28430-28430/? E/Diag_Lib:  Diag_LSM_Init: Failed to open handle to diag driver, error = 13
2020-05-01 10:39:37.928 28430-28430/? E/QCOMSysDaemon:  Diag_LSM_Init failed : 0
2020-05-01 10:39:38.265 25400-25693/? I/DeltaChat: ThreadId(47) src/dc_receive_imf.rs:42: Receiving message DeltaChat/3028...
2020-05-01 10:39:38.344 25400-25693/? I/DeltaChat: ThreadId(47) src/e2ee.rs:236: Detected Autocrypt-mime message
2020-05-01 10:39:38.401 25400-25693/? W/DeltaChat: ThreadId(47) src/mimeparser.rs:419: Ignoring nested protected headers
2020-05-01 10:39:38.403 25400-25693/? I/DeltaChat: ThreadId(47) src/dc_receive_imf.rs:1141: not creating ad-hoc group: too few contacts
2020-05-01 10:39:38.426 25400-25693/? I/DeltaChat: ThreadId(47) src/dc_receive_imf.rs:671: Message has 1 parts and is assigned to chat #Chat#429.
2020-05-01 10:39:38.426 25400-25693/? I/DeltaChat: ThreadId(47) src/dc_receive_imf.rs:215: received message 3028 has Message-Id: Mr.k4kxVA36HVj.P2REXFd5YXc@gmx.de
2020-05-01 10:39:38.446 25400-25693/? I/DeltaChat: ThreadId(47) src/imap/mod.rs:662: 1 mails read from "DeltaChat".
2020-05-01 10:39:38.582 25400-25693/? I/DeltaChat: ThreadId(47) src/imap/mod.rs:597: fetch_new_messages: ignoring uid 3028, last seen was 3028
2020-05-01 10:39:38.583 25400-25693/? I/DeltaChat: ThreadId(47) src/imap/mod.rs:662: 0 mails read from "DeltaChat".
2020-05-01 10:39:38.583 25400-25693/? I/DeltaChat: ThreadId(47) src/job_thread.rs:112: MVBOX-fetch done in 675 ms.
2020-05-01 10:39:38.586 25400-25693/? I/DeltaChat: ThreadId(47) src/job_thread.rs:177: MVBOX-IDLE started...
2020-05-01 10:39:38.693 25400-25693/? I/DeltaChat: ThreadId(47) src/imap/idle.rs:91: Idle entering wait-on-remote state
2020-05-01 10:39:41.206 469-469/? I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2020-05-01 10:39:42.540 469-469/? I/chatty: uid=1000(system) /system/bin/surfaceflinger identical 16 lines
2020-05-01 10:39:42.540 469-469/? I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2020-05-01 10:39:42.931 28433-28433/? E/QCOMSysDaemon: Can't find/open bootselect node: (No such file or directory)
2020-05-01 10:39:42.932 28433-28433/? I/QCOMSysDaemon: Starting qcom system daemon
2020-05-01 10:39:42.916 28433-28433/? W/qcom-system-dae: type=1400 audit(0.0:12687): avc: denied { read write } for name="diag" dev="tmpfs" ino=17517 scontext=u:r:vendor_qcomsysd:s0 tcontext=u:object_r:diag_device:s0 tclass=chr_file permissive=0
2020-05-01 10:39:42.934 28433-28433/? E/Diag_Lib:  Diag_LSM_Init: Failed to open handle to diag driver, error = 13
2020-05-01 10:39:42.934 28433-28433/? E/QCOMSysDaemon:  Diag_LSM_Init failed : 0
2020-05-01 10:39:44.271 469-469/? I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2020-05-01 10:39:44.539 469-469/? I/chatty: uid=1000(system) /system/bin/surfaceflinger identical 7 lines
2020-05-01 10:39:44.539 469-469/? I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2020-05-01 10:39:45.369 595-595/? D/ThermalHAL-TARGET: Entering get_temperatures
2020-05-01 10:39:45.369 595-595/? D/ThermalHAL-TARGET: Entering get_temperatures
2020-05-01 10:39:45.369 595-595/? D/ThermalHAL-UTIL: Entering get_temperature_for_all
2020-05-01 10:39:45.369 595-595/? D/ThermalHAL-UTIL: Entering read_temperature
2020-05-01 10:39:45.371 595-595/? I/chatty: uid=1000(system) thermal@1.0-ser identical 9 lines
2020-05-01 10:39:45.374 595-595/? D/ThermalHAL-UTIL: Entering read_temperature
2020-05-01 10:39:45.377 1757-1757/? D/PowerUI: BatteryTempWarning updateTemperatureWarning
2020-05-01 10:39:45.377 1757-1757/? D/PowerUI: BatteryTempWarning mBatteryTemp=258, mThresholdTemp=550.0, mThresholdLowTemp=0.0
2020-05-01 10:39:46.270 469-469/? I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2020-05-01 10:39:47.555 469-469/? I/chatty: uid=1000(system) /system/bin/surfaceflinger identical 16 lines
2020-05-01 10:39:47.556 469-469/? I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2020-05-01 10:39:47.936 28434-28434/? W/qcom-system-dae: type=1400 audit(0.0:12688): avc: denied { read write } for name="diag" dev="tmpfs" ino=17517 scontext=u:r:vendor_qcomsysd:s0 tcontext=u:object_r:diag_device:s0 tclass=chr_file permissive=0
2020-05-01 10:39:47.946 28434-28434/? E/QCOMSysDaemon: Can't find/open bootselect node: (No such file or directory)
2020-05-01 10:39:47.946 28434-28434/? I/QCOMSysDaemon: Starting qcom system daemon
2020-05-01 10:39:47.947 28434-28434/? E/Diag_Lib:  Diag_LSM_Init: Failed to open handle to diag driver, error = 13
2020-05-01 10:39:47.947 28434-28434/? E/QCOMSysDaemon:  Diag_LSM_Init failed : 0
2020-05-01 10:39:49.318 469-469/? I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2020-05-01 10:39:49.570 469-469/? I/chatty: uid=1000(system) /system/bin/surfaceflinger identical 7 lines
2020-05-01 10:39:49.570 469-469/? I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2020-05-01 10:39:49.610 1123-2415/? D/WificondControl: Scan result ready event
2020-05-01 10:39:49.612 804-20228/? I/LOWI-8.6.0.33: [LOWI-Scan] lowi_close_record:Scan done in 6372836ms, 7 APs in scan results
2020-05-01 10:39:49.613 804-881/? I/LOWI-8.6.0.33: [LOWIUtils] responseToOutPostcard - TO: GTP-FDAL, FROM:   LOWI-SERVER, RESP:  LOWI_ASYNC_DISCOVERY_SCAN_RESULTS
2020-05-01 10:39:49.617 806-963/? W/XTCC-6.2.0.6: [WifiScanner] WiFi scan result : [7] AP's, async result: 1
2020-05-01 10:39:51.235 469-469/? I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2020-05-01 10:39:51.586 469-469/? I/chatty: uid=1000(system) /system/bin/surfaceflinger identical 7 lines
2020-05-01 10:39:51.586 469-469/? I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2020-05-01 10:39:52.950 28436-28436/? E/QCOMSysDaemon: Can't find/open bootselect node: (No such file or directory)
2020-05-01 10:39:52.950 28436-28436/? I/QCOMSysDaemon: Starting qcom system daemon
2020-05-01 10:39:52.936 28436-28436/? W/qcom-system-dae: type=1400 audit(0.0:12689): avc: denied { read write } for name="diag" dev="tmpfs" ino=17517 scontext=u:r:vendor_qcomsysd:s0 tcontext=u:object_r:diag_device:s0 tclass=chr_file permissive=0
2020-05-01 10:39:52.952 28436-28436/? E/Diag_Lib:  Diag_LSM_Init: Failed to open handle to diag driver, error = 13
2020-05-01 10:39:52.952 28436-28436/? E/QCOMSysDaemon:  Diag_LSM_Init failed : 0
2020-05-01 10:39:54.290 469-469/? I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2020-05-01 10:39:54.599 469-469/? I/chatty: uid=1000(system) /system/bin/surfaceflinger identical 7 lines
2020-05-01 10:39:54.600 469-469/? I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2020-05-01 10:39:55.256 1757-1757/? D/GsensorListener: [SW_SAR] GsensorListener setTransmitPower key = 1, value = 1
2020-05-01 10:39:55.256 1757-1757/? D/TelephonyManager: [SW_SAR] Telephonymanager setTransmitPower
2020-05-01 10:39:55.257 1894-2212/? E/PhoneInterfaceManager: [PhoneIntfMgr] [SW_SAR] phone get successful
2020-05-01 10:39:55.259 2066-2066/? D/QcrilMsgTunnelIfaceManager: handleMessage what = 1
2020-05-01 10:39:55.259 2066-2066/? I/QcrilOemhookMsgTunnel: [0]invokeOemRilRequestRaw: serial=3599 length=24
2020-05-01 10:39:55.268 2066-2127/? I/QcrilOemhookMsgTunnel: [0]processOemHookResponse serial no: 3599 error: 0length=0
2020-05-01 10:39:55.269 2066-2066/? D/QcrilMsgTunnelIfaceManager: handleMessage what = 2
2020-05-01 10:39:55.297 469-469/? I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2020-05-01 10:39:56.298 469-469/? I/chatty: uid=1000(system) /system/bin/surfaceflinger identical 12 lines
2020-05-01 10:39:56.298 469-469/? I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2020-05-01 10:39:56.402 1757-1757/? D/GsensorListener: [SW_SAR] GsensorListener setTransmitPower key = 1, value = 0
2020-05-01 10:39:56.402 1757-1757/? D/TelephonyManager: [SW_SAR] Telephonymanager setTransmitPower
```

**Comment by r10s** [comment]
@Hocuri great, so we're getting closer, esp the finding it also happes testrun-to-testrun is reall important. can you please file a separate issue for that, it is not yet totally clear to me what belongs to what, if it only happes with account switching  etc. :)

**Pull request merged**
