### PR TITLE
adapt js to new webxdc-update-api

### PR DESCRIPTION
**Pull request by r10s**
ui part of https://github.com/deltachat/deltachat-core-rust/pull/3081

### CODE REVIEW

**Comment by r10s** [comment]
tested it roughly, seems to work :) requires https://github.com/deltachat/deltachat-core-rust/pull/3081

once this and https://github.com/deltachat/deltachat-core-rust/pull/3081 are merged, we should file corresponding issues/pr for ios/desktop.

**Comment by r10s** [comment]
hm, for the poll webxdc, creating a draft and already voting in the draft, loses the state on the sending device. the other device seems to be okay (did a quick test with two devices only, did not test other apps)

**Review by Simon-Laux — APPROVED** [review]
Change is smaller than what I imagined it to be, good job!

**Review by adbenitez — APPROVED** [review]

**Comment by adbenitez** [comment]
> hm, for the poll webxdc, creating a draft and already voting in the draft, loses the state on the sending device. the other device seems to be okay (did a quick test with two devices only, did not test other apps)

I checked the code of the poll app, the issue is that you are loading the state with the old `getAllUpdates()` which is always empty now and in the listener given to `setUpdateListener()` you ignore events from `selfAddr` so the app can't restore the state only from what is given to `setUpdateListener()` needs to be reworked to not ignore `selfAddr` updates, in general it always was a good practice to process events even from `selfAddr` instead of what you did in the poll app ;P

**Comment by r10s** [comment]
thanks for checking webxdc-poll. indeed, that app does not use good practices and need to be adapted.

**Pull request merged**
