### PR TITLE
Better build instructions in Readme

### PR DESCRIPTION
**Pull request by Hocuri**
@rezazarchi do you think this would have helped with #2230 ?

### CODE REVIEW

**Comment by rezazarchi** [comment]
Hey. I reviewed changes and I think they can be helpful for that issue. Thank you!

**Review by rezazarchi — APPROVED** [review]

**Review by r10s — COMMENTED** [review]
so `ANDROID_NDK_ROOT` should be used instead of `ANDROID_NDK`?

is there some link to that somewhere? just asking as i am using `ANDROID_NDK` and have `ANDROID_NDK_ROOT` unset - and everything works as expected :)

**Comment by rezazarchi** [comment]
> so `ANDROID_NDK_ROOT` should be used instead of `ANDROID_NDK`?
> 
> is there some link to that somewhere? just asking as i am using `ANDROID_NDK` and have `ANDROID_NDK_ROOT` unset - and everything works as expected :)

I tested them with `ANDROID_NDK_ROOT` in my environment and it works. I think `ANDROID_NDK` is not correct.

**Comment by r10s** [comment]
it is a mess ...

**Comment by Hocuri** [comment]
> so `ANDROID_NDK_ROOT` should be used instead of `ANDROID_NDK`?

Before, the Readme once told to use ANDROID_NDK and once ANDROID_NDK_ROOT, I just made it match. Seems to me like doesn't matter (and if I understand the syntax there correctly, at the beginning of ndk-make.sh, it looks for all of them).

**Comment by Hocuri** [comment]
By the way:

<pre>$ grep ANDROID_NDK -R 2&gt;/dev/null
<font color="#AA00AA">jni/Android.mk</font><font color="#00AAAA">:</font>LOCAL_CFLAGS 	+= -D<font color="#FF5555"><b>ANDROID_NDK</b></font> -DDISABLE_IMPORTGL -fno-strict-aliasing -DAVOID_TABLES -DANDROID_TILE_BASED_DECODE -DANDROID_ARMV6_IDCT -ffast-math -D__STDC_CONSTANT_MACROS
<font color="#AA00AA">.github/workflows/preview-apk.yml</font><font color="#00AAAA">:</font>          <font color="#FF5555"><b>ANDROID_NDK</b></font>_ROOT: ${{ steps.setup-ndk.outputs.ndk-path }}
<font color="#AA00AA">.github/workflows/preview-apk.yml</font><font color="#00AAAA">:</font>          export PATH=&quot;${PATH}:${<font color="#FF5555"><b>ANDROID_NDK</b></font>_ROOT}/toolchains/llvm/prebuilt/linux-x86_64/bin/:${<font color="#FF5555"><b>ANDROID_NDK</b></font>_ROOT}&quot;
<font color="#AA00AA">Dockerfile</font><font color="#00AAAA">:</font>ENV <font color="#FF5555"><b>ANDROID_NDK</b></font>_ROOT ${ANDROID_SDK_ROOT}/ndk-bundle
<font color="#AA00AA">Dockerfile</font><font color="#00AAAA">:</font>ENV PATH ${PATH}:${<font color="#FF5555"><b>ANDROID_NDK</b></font>_ROOT}/toolchains/llvm/prebuilt/linux-x86_64/bin/:${<font color="#FF5555"><b>ANDROID_NDK</b></font>_ROOT}
<font color="#AA00AA">README.md</font><font color="#00AAAA">:</font>`<font color="#FF5555"><b>ANDROID_NDK</b></font>_ROOT` environment variable to point to the Android NDK
<font color="#AA00AA">README.md</font><font color="#00AAAA">:</font>7. Export the folder path to your environment as `<font color="#FF5555"><b>ANDROID_NDK</b></font>` and add it to `PATH`.
<font color="#AA00AA">README.md</font><font color="#00AAAA">:</font>   `export <font color="#FF5555"><b>ANDROID_NDK</b></font>=/home/USERNAME/android-ndk-r…`
<font color="#AA00AA">README.md</font><font color="#00AAAA">:</font>   `export PATH=$PATH:$<font color="#FF5555"><b>ANDROID_NDK</b></font>`.
<font color="#AA00AA">ndk-make.sh</font><font color="#00AAAA">:</font>: &quot;${<font color="#FF5555"><b>ANDROID_NDK</b></font>_ROOT:=$<font color="#FF5555"><b>ANDROID_NDK</b></font>_HOME}&quot;
<font color="#AA00AA">ndk-make.sh</font><font color="#00AAAA">:</font>: &quot;${<font color="#FF5555"><b>ANDROID_NDK</b></font>_ROOT:=$<font color="#FF5555"><b>ANDROID_NDK</b></font>}&quot;
<font color="#AA00AA">ndk-make.sh</font><font color="#00AAAA">:</font>if test ! -z &quot;$<font color="#FF5555"><b>ANDROID_NDK</b></font>_ROOT&quot;; then
<font color="#AA00AA">ndk-make.sh</font><font color="#00AAAA">:</font>    TOOLCHAIN=&quot;$<font color="#FF5555"><b>ANDROID_NDK</b></font>_ROOT/toolchains/llvm/prebuilt/$NDK_HOST_TAG&quot;</pre>

**Comment by Hocuri** [comment]
> > so `ANDROID_NDK_ROOT` should be used instead of `ANDROID_NDK`?
> 
> Before, the Readme once told to use ANDROID_NDK and once ANDROID_NDK_ROOT, I just made it the same in all places. Seems to me like doesn't matter (and if I understand the syntax there correctly, at the beginning of ndk-make.sh, it looks for all of them).

**Review by r10s — APPROVED** [review]
not sure if it matters, however, yes, using the same  name throughout the readme makse definetely sense.

if it turns out, `ANDROID_NDK` is still needed on some environments, we can add an additional hint  as needed.

**Comment by r10s** [comment]
@rezazarchi @Hocuri what does a `echo $ANDROID_NDK` print on your machines? if it is really empty, it seems not to be needed :)

**Comment by Hocuri** [comment]
Yup, it's empty.

**Comment by rezazarchi** [comment]
> 

Nothing.

**Pull request merged**
