### PR TITLE
fix map

### LINKED ISSUE #1112: map broken
the map, that is available as an experimental feature, is currently broken, see https://github.com/deltachat/deltachat-android/pull/1109#issuecomment-552207204

### PR DESCRIPTION
**Pull request by cyBerta**
closes #1112 

deltachat/deltachat-core-rust#798 needs to be fixed still.

### CODE REVIEW

**Comment by r10s** [comment]
great, tested that on my androd7 motog this fixes the crash :)

there may still be issues in location streaming as such with the new rust-core, but this is out of scope of this pr :)

@cyBerta is the "wip" thingie still correct?

**Comment by cyBerta** [comment]
I've found a bug while debugging https://github.com/deltachat/deltachat-core-rust/issues/798.

**Comment by r10s** [comment]
> I've found a bug while debugging deltachat/deltachat-core-rust#798.

only found? or fixed by the commit above?

**Comment by cyBerta** [comment]
found and fixed :)

**Pull request merged**
