### PR TITLE
search during forwarding, forward to archives, forward to new contacts

### PR DESCRIPTION
**Pull request by r10s**

### CODE REVIEW

**Comment by r10s** [comment]
one more thing:

- the three-point-menu right in the titlebar should be hidden as well

**Comment by cyBerta** [comment]
@r10s all mentioned issues have  been addressed

**Comment by r10s** [comment]
cool, will test a bit :)

**Comment by r10s** [comment]
great. some comments:

- it's already better that the system-back-key does not close the app, however, i'd expect the last activity (the chat) to appear, not the chatlist

- bikeshedding: is there some additional space right of the "search" button? looks to be as if it should be more to the right.

however, it's a great progress, so i merge this, we can iterate from there and also target https://github.com/deltachat/deltachat-android/issues/901 then.

**Pull request merged**
